/**
 * Console pages for PHP admin menu items that are not already a console route.
 * `api` is under /api/v1. `php` is the AMPL.BAadmin file the query comes from.
 */
export const phpScreens = [
  { slug: "business-dashboard", title: "Business Dashboard", php: "main_dashboard.php", api: "admin/panel-dashboards/main", kind: "summary" },
  { slug: "ceo-matrix", title: "CEO Decision Matrix", php: "ceo_decision_matrix.php", api: "admin/menu/ceo-matrix", kind: "summary" },
  { slug: "seller-dashboard", title: "Seller Overview", php: "seller_dashboard.php", api: "admin/panel-dashboards/sellers", kind: "summary" },
  { slug: "seller-approval", title: "Seller Approval", php: "seller.php", api: "admin/vendors/verification", kind: "list" },
  { slug: "cost-margin", title: "Cost & Margin Management", php: "product_cost_management.php", api: "admin/pricing/cost-config", kind: "list" },
  { slug: "product-dashboard", title: "Product Dashboard", php: "product_dashboard.php", api: "admin/products/summary", kind: "summary" },
  { slug: "product-management", title: "Product Management Dashboard", php: "product_management_dashboard.php", api: "admin/panel-dashboards/products", kind: "summary" },
  { slug: "categories", title: "Category", php: "category.php", api: "admin/catalog/categories", kind: "list" },
  { slug: "brands", title: "Brand", php: "brand.php", api: "admin/catalog/brands", kind: "list" },
  { slug: "feature-categories", title: "Feature Category", php: "feature_category.php", api: "admin/menu/feature-categories", kind: "list" },
  { slug: "crop-menu", title: "Crop Menu", php: "shop_topics.php", api: "admin/menu/shop-topics", kind: "list", query: { type: "crop" } },
  { slug: "attributes", title: "Configuration Attributes", php: "manage_conf_attributes.php", api: "admin/catalog/attributes", kind: "list" },
  { slug: "hsn-codes", title: "HSN Code", php: "manage_hsncode.php", api: "admin/catalog/hsn-codes", kind: "list" },
  { slug: "tax-classes", title: "Tax Class", php: "manage_tax_class.php", api: "admin/catalog/tax-classes", kind: "list" },
  { slug: "return-policies", title: "Return Policy", php: "manage_return_policy.php", api: "admin/catalog/return-policies", kind: "list" },
  { slug: "master-nrv", title: "Master NRV", php: "add_master_nrv.php", api: "admin/pricing/master-nrv", kind: "list" },
  { slug: "package-boxes", title: "Vendor Package Boxes", php: "vendor_package_boxes.php", api: "admin/shipping/package-boxes", kind: "list" },
  { slug: "seller-scores", title: "Score Management", php: "score_management.php", api: "admin/vendors/scores", kind: "list" },
  { slug: "home-banner", title: "Home Banner", php: "newhomepage_website.php", api: "admin/cms/home-sections", kind: "list" },
  { slug: "blogs", title: "Blogs", php: "blogs.php", api: "admin/cms/blogs", kind: "list" },
  { slug: "custom-pages", title: "Custom Add Pages", php: "pages_custom.php", api: "admin/cms/pages", kind: "list" },
  { slug: "seo-pages", title: "Custom Page", php: "meta.php", api: "admin/pages", kind: "list" },
  { slug: "cart-tracking", title: "Cart Tracking", php: "engagement_panel.php", api: "admin/menu/cart-tracking", kind: "list" },
  { slug: "recently-viewed", title: "Recently Viewed", php: "engagement_panel.php", api: "admin/menu/recently-viewed", kind: "list" },
  { slug: "order-dashboard", title: "Sales Dashboard", php: "order_management_dashboard.php", api: "admin/panel-dashboards/orders", kind: "summary" },
  { slug: "whatsapp-orders", title: "WhatsApp Orders", php: "whatsapp_orders.php", api: "admin/orders-whatsapp", kind: "list" },
  { slug: "b2b-buyers", title: "Buyers", php: "b2b_orders/buyers.php", api: "admin/b2b/buyers", kind: "list" },
  { slug: "b2b-rfqs", title: "RFQs", php: "b2b_orders/rfqs.php", api: "admin/b2b/rfqs", kind: "list" },
  { slug: "b2b-quotations", title: "B2B Quotations", php: "b2b_orders/b2b_quotations.php", api: "admin/b2b/quotations", kind: "list" },
  { slug: "b2b-catalog", title: "Catalog / Products", php: "b2b_orders/catalog.php", api: "admin/menu/b2b-catalog", kind: "list" },
  { slug: "b2b-orders", title: "B2B Orders List", php: "b2b_orders/b2b_order_list.php", api: "admin/b2b/orders", kind: "list" },
  { slug: "b2b-reports", title: "B2B Reports", php: "b2b_orders/reports.php", api: "admin/menu/b2b-reports", kind: "summary" },
  { slug: "bulk-inquiries", title: "Bulk Inquiry", php: "bulk_orders/bulk_inquiry.php", api: "admin/bulk-orders/inquiries", kind: "list" },
  { slug: "lead-dashboard", title: "Lead Dashboard", php: "lead_dashboard.php", api: "admin/crm/dashboard", kind: "summary" },
  { slug: "crm-leads", title: "CRM Lead Sheet", php: "crm_leads.php", api: "admin/crm/leads", kind: "list" },
  { slug: "all-leads", title: "Manage All Leads", php: "manager_all_leads.php", api: "admin/crm/legacy-leads", kind: "list" },
  { slug: "unassigned-leads", title: "Unassigned Leads", php: "pending_leads.php", api: "admin/menu/unassigned-leads", kind: "list" },
  { slug: "dead-leads", title: "Dead Leads", php: "dead_leads.php", api: "admin/menu/dead-leads", kind: "list" },
  { slug: "ai-calls", title: "AI Calling Agent", php: "vapi_calls.php", api: "admin/crm/ai-calls", kind: "list" },
  { slug: "search-terms", title: "Customer Tracking", php: "customer_search_tracking.php", api: "admin/menu/search-terms", kind: "list" },
  { slug: "sales-targets", title: "Sales Target Management", php: "sales_target_management.php", api: "admin/sales/targets", kind: "list" },
  { slug: "sales-performance", title: "Team Performance", php: "sales_performance_report.php", api: "admin/sales/dashboard", kind: "summary" },
  { slug: "ops-center", title: "Operations Center", php: "operations_center/index.php", api: "admin/operations/center", kind: "summary" },
  { slug: "ops-team", title: "Operations Dashboard", php: "operations_team/dashboard.php", api: "admin/operations/team", kind: "summary" },
  { slug: "ops-setup", title: "Setup", php: "operations_team/setup.php", api: "admin/operations/kpi-targets", kind: "list" },
  { slug: "my-orders", title: "My Orders", php: "operations_team/agent_orders.php", api: "admin/operations/assignments", kind: "list" },
  { slug: "shiprocket-orders", title: "Shiprocket Orders", php: "shiprocket_orders_report.php", api: "admin/shipments", kind: "list" },
  { slug: "delhivery-orders", title: "Delhivery Orders", php: "shipment_order_delhivery.php", api: "admin/menu/delhivery-shipments", kind: "list" },
  { slug: "weight-discrepancy", title: "Weight Discrepancy", php: "weight_discrapancy.php", api: "admin/shipping/weight-discrepancies", kind: "list" },
  { slug: "return-shipments", title: "Return Shipments", php: "manage_returns.php", api: "admin/returns", kind: "list" },
  { slug: "courier-slabs", title: "Courier Cost Slab", php: "courier_cost_slab_master.php", api: "admin/shipping/courier-slabs", kind: "list" },
  { slug: "pincodes", title: "Shiprocket Serviceability", php: "courier_serviceability.php", api: "admin/shipping/pincodes", kind: "list" },
  { slug: "pickup-requests", title: "Pickup Update", php: "manage_pickup_requests.php", api: "admin/menu/pickup-requests", kind: "list" },
  { slug: "pickup-addresses", title: "Pickup Addresses", php: "pickup_addresses.php", api: "admin/bulk-orders/warehouses", kind: "list" },
  { slug: "b2b-ops", title: "Operations Queue", php: "b2b_orders/ops_queue.php", api: "admin/menu/b2b-ops", kind: "list" },
  { slug: "b2b-logistics", title: "B2B Logistics", php: "b2b_orders/logistics.php", api: "admin/menu/b2b-shipments", kind: "list" },
  { slug: "agent-report", title: "Agent Report", php: "operations_team/agent_report.php", api: "admin/operations/agents", kind: "list" },
  { slug: "smtp", title: "SMTP Settings", php: "smtp_settings.php", api: "admin/settings/smtp", kind: "summary" },
  { slug: "sms", title: "SMS Settings", php: "sms_settings.php", api: "admin/settings/sms", kind: "summary" },
  { slug: "fixed-expenses", title: "Fixed Expenses", php: "fixed_expenses.php", api: "admin/finance/fixed-expenses", kind: "list" },
  { slug: "expense-limits", title: "Expense Limit Dashboard", php: "expense_limit_dashboard.php", api: "admin/finance/expense-limits", kind: "summary" },
  { slug: "payouts", title: "Payout Vendor", php: "payout_new.php", api: "admin/payouts", kind: "list" },
  { slug: "hold-ledger", title: "Hold Ledger", php: "hold_ledger.php", api: "admin/finance/hold-ledger", kind: "list" },
  { slug: "b2b-settlements", title: "B2B Settlements", php: "b2b_orders/settlements.php", api: "admin/b2b/settlements", kind: "list" },
  { slug: "refunds", title: "Refund Return Report", php: "returns_refunds_report.php", api: "admin/refunds", kind: "list" },
  { slug: "finance-payout", title: "Finance Payout Dashboard", php: "finance_payout_dashboard.php", api: "admin/panel-dashboards/finance", kind: "summary" },
  { slug: "chat-sessions", title: "Chatbot Logs", php: "chat_logs.php", api: "admin/menu/chat-sessions", kind: "list" },
  { slug: "requirement-requests", title: "Requirement Requests", php: "requirement_requests.php", api: "admin/menu/requirement-requests", kind: "list" },
  { slug: "vacancies", title: "Hiring Vacancies", php: "vacancies.php", api: "admin/menu/vacancies", kind: "list" },
  { slug: "pending-reviews", title: "Pending Reviews", php: "product_review.php", api: "admin/menu/pending-reviews", kind: "list" },
  { slug: "reviews", title: "Manage Reviews", php: "manage_review.php", api: "admin/reviews", kind: "list" },
  { slug: "customers", title: "Manage All User", php: "app-user.php", api: "admin/customers", kind: "list" },
  { slug: "staff", title: "Staff User", php: "manage-staff.php", api: "admin/users", kind: "list" },
  { slug: "roles", title: "Manage Role", php: "manage-role.php", api: "admin/access/roles", kind: "summary" },
  { slug: "menus", title: "Menu Master", php: "menu-master.php", api: "admin/access/menus", kind: "summary" },
  { slug: "reject-reasons", title: "Manage Reject Reason", php: "reject-reason.php", api: "admin/masters/reject-reasons", kind: "list" },
  { slug: "shipping-slabs", title: "Manage Shipping Slabs", php: "manage_shipping_slabs.php", api: "admin/shipping/slabs", kind: "list" },
  { slug: "minimums", title: "Minimum Order & COD", php: "manage_minimum_order.php", api: "admin/settings/minimums", kind: "summary" },
  { slug: "cod-rules", title: "Manage COD State Rule", php: "manage_cod_state_rule.php", api: "admin/shipping/cod-rules", kind: "list" },
  { slug: "system-settings", title: "General Settings", php: "system_settings.php", api: "admin/settings/system", kind: "summary" },
  { slug: "languages", title: "Language Settings", php: "language_settings.php", api: "admin/settings/languages", kind: "list" },
  { slug: "currency", title: "Currency Settings", php: "currency_settings.php", api: "admin/masters/currency", kind: "list" },
  { slug: "email-templates", title: "Email Template", php: "email_template.php", api: "admin/settings/email-templates", kind: "list" },
];

const bySlug = new Map(phpScreens.map((screen) => [screen.slug, screen]));

export function getPhpScreen(slug) {
  return bySlug.get(slug) ?? null;
}
