import { parityLive, parityLivePaths, parityPages } from "@/lib/content/admin/resources/parity";
import { portLive, portLivePaths, portPages } from "@/lib/content/admin/resources/port";

/**
 * Admin list screens the Node API already serves (resource engine).
 * `page` is the PHP menu link `adminCan` checks. `permission` is the Next sidebar key.
 */
export const LIVE_RESOURCES = {
  orders: { path: "/lists/orders", page: "manage_orders.php", permission: "orders" },
  products: { path: "/lists/products", page: "manage_product.php", permission: "products" },
  inventory: { path: "/inventory", page: "manage_product.php", permission: "products" },
  "inventory.history": { path: "/inventory/movements", page: "manage_product.php", permission: "products" },
  "products.pending": { path: "/products/pending", page: "pending_products.php", permission: "products.approval" },
  "orders.invoices": { path: "/invoices", page: "manage_orders.php", permission: "orders.invoices" },
  "orders.transactions": { path: "/reports/transactions", page: "orders_report.php", permission: "orders.transactions" },
  "orders.whatsapp": { path: "/orders-whatsapp", page: "whatsapp_orders.php", permission: "orders.whatsapp" },
  "orders.srCheckout": { path: "/sr-checkout", page: "manage_orders.php", permission: "orders.srCheckout" },
  "vendors.scores": { path: "/vendors/scores", page: "score_management.php", permission: "vendors.scores" },
  "vendors.reports": { path: "/reports/vendors", page: "seller.php", permission: "vendors.reports" },
  shipping: { path: "/shipments", page: "shiprocket_orders_report.php", permission: "shipping" },
  "shipping.codRules": { path: "/shipping/cod-rules", page: "manage_cod_state_rule.php", permission: "shipping.rules" },
  returns: { path: "/returns", page: "manage_returns.php", permission: "returns" },
  "returns.reasons": { path: "/returns/reasons", page: "reject-reason.php", permission: "returns" },
  refunds: { path: "/refunds", page: "returns_refunds_report.php", permission: "refunds" },
  rto: { path: "/rto", page: "manage_orders.php", permission: "rto" },
  customers: { path: "/customers", page: "app-user.php", permission: "customers" },
  vendors: { path: "/vendors", page: "seller.php", permission: "vendors" },
  "vendors.verification": { path: "/vendors/verification", page: "seller.php", permission: "vendors.verification" },
  "customers.coupons": { path: "/coupons", page: "coupon.php", permission: "customers.coupons" },
  "customers.reviews": { path: "/reviews", page: "manage_review.php", permission: "customers.reviews" },
  users: { path: "/users", page: "manage-staff.php", permission: "users" },
  audit: { path: "/audit-log", page: "manage-role.php", permission: "audit" },
  support: { path: "/support/tickets", page: "admin_dashboard.php", permission: "support" },
  "finance.wallet": { path: "/finance/wallet-withdrawals", page: "finance_payout_dashboard.php", permission: "finance.wallet" },
  "cms.blogs": { path: "/cms/blogs", page: "blogs.php", permission: "cms" },
  "cms.faqs": { path: "/cms/faqs", page: "manage_product.php", permission: "cms" },
  "cms.footer": { path: "/cms/footer", page: "system_settings.php", permission: "cms" },
  "cms.events": { path: "/cms/events", page: "blogs.php", permission: "cms" },
  "settings.emailTemplates": { path: "/settings/email-templates", page: "email_template.php", permission: "settings" },
  "settings.languages": { path: "/settings/languages", page: "language_settings.php", permission: "settings" },
  "masters.currency": { path: "/masters/currency", page: "currency_settings.php", permission: "masters" },
  "masters.geography": { path: "/masters/geography", page: "system_settings.php", permission: "masters" },
  "masters.rejectReasons": { path: "/masters/reject-reasons", page: "reject-reason.php", permission: "masters" },
  "crm.circles": { path: "/crm/circles", page: "crm_leads.php", permission: "crm.circles" },
  "finance.fixedExpenses": { path: "/finance/fixed-expenses", page: "fixed_expenses.php", permission: "finance.expenses" },
  "pricing.masterNrv": { path: "/pricing/master-nrv", page: "add_master_nrv.php", permission: "pricing.masterNrv" },
  "pricing.commission": { path: "/pricing/commission-rules", page: "product_cost_management.php", permission: "pricing.commission" },
  "pricing.costConfig": { path: "/pricing/cost-config", page: "product_cost_management.php", permission: "pricing.costConfig" },
  "shipping.courierSlabs": { path: "/shipping/courier-slabs", page: "courier_cost_slab_master.php", permission: "shipping.rates" },
  "shipping.slabs": { path: "/shipping/slabs", page: "manage_shipping_slabs.php", permission: "shipping.rates" },
  "shipping.otherCharges": { path: "/shipping/other-charges", page: "courier_cost_slab_master.php", permission: "shipping.rates" },
  "shipping.boxes": { path: "/shipping/package-boxes", page: "vendor_package_boxes.php", permission: "shipping.boxes" },
  "shipping.weight": { path: "/shipping/weight-discrepancies", page: "weight_discrapancy.php", permission: "shipping.weight" },
  "shipping.pincodes": { path: "/shipping/pincodes", page: "courier_serviceability.php", permission: "shipping.pincodes" },
  "catalog.categories": { path: "/catalog/categories", page: "category.php", permission: "catalog.categories" },
  "catalog.brands": { path: "/catalog/brands", page: "brand.php", permission: "catalog.brands" },
  "catalog.attributes": { path: "/catalog/attributes", page: "manage_conf_attributes.php", permission: "catalog.attributes" },
  "catalog.tax": { path: "/catalog/tax-classes", page: "manage_tax_class.php", permission: "catalog.tax" },
  "catalog.hsn": { path: "/catalog/hsn-codes", page: "manage_hsncode.php", permission: "catalog.hsn" },
  "catalog.returnPolicies": { path: "/catalog/return-policies", page: "manage_return_policy.php", permission: "catalog.returnPolicies" },
  "payouts.items": { path: "/payouts/items", page: "payout_new_items.php", permission: "payouts" },
  payouts: { path: "/payouts", page: "payout_new_items.php", permission: "payouts" },
  "payouts.access": { path: "/payouts/access", page: "vendor_payout_access_settings.php", permission: "payouts.access" },
  "payouts.legacy": { path: "/payouts/legacy", page: "payout_new.php", permission: "payouts" },
  "finance.ledger": { path: "/finance/ledger", page: "payout_finance.php", permission: "finance.ledger" },
  "finance.holdLedger": { path: "/finance/hold-ledger", page: "hold_ledger.php", permission: "finance.holdLedger" },
  "finance.cod": { path: "/finance/cod-reconciliation", page: "payout_finance.php", permission: "finance" },
  "finance.tax": { path: "/finance/gst-summary", page: "payout_finance.php", permission: "finance.tax" },
  "crm.leads": { path: "/crm/leads", page: "crm_leads.php", permission: "crm.leads" },
  "crm.followUps": { path: "/crm/follow-ups", page: "crm_leads.php", permission: "crm.leads" },
  "crm.legacy": { path: "/crm/legacy-leads", page: "manager_all_leads.php", permission: "crm.legacy" },
  "crm.whatsapp": { path: "/crm/whatsapp-sessions", page: "whatsapp_leads.php", permission: "crm.whatsapp" },
  "crm.aiCalls": { path: "/crm/ai-calls", page: "vapi_calls.php", permission: "crm.aiCalls" },
  "crm.callAudit": { path: "/crm/call-audits", page: "call_audit.php", permission: "crm.callAudit" },
  "sales.targets": { path: "/sales/targets", page: "sales_target_management.php", permission: "sales.targets" },
  "sales.salary": { path: "/sales/salary-structures", page: "sales_target_management.php", permission: "sales.salary" },
  "sales.achievements": { path: "/sales/achievements", page: "sales_target_management.php", permission: "sales.targets" },
  "sales.payouts": { path: "/sales/payouts", page: "sales_target_management.php", permission: "sales.payouts" },
  "sales.prepaid": { path: "/sales/prepaid-incentive-config", page: "sales_prepaid_incentive_setup.php", permission: "sales.salary" },
  "sales.team": { path: "/sales/team", page: "sales_target_management.php", permission: "sales" },
  "b2b.buyers": { path: "/b2b/buyers", page: "b2b_orders/buyers.php", permission: "b2b.buyers" },
  "b2b.rfqs": { path: "/b2b/rfqs", page: "b2b_orders/rfqs.php", permission: "b2b.rfqs" },
  "b2b.quotations": { path: "/b2b/quotations", page: "b2b_orders/b2b_quotations.php", permission: "b2b.quotations" },
  "b2b.orders": { path: "/b2b/orders", page: "b2b_orders/b2b_order_list.php", permission: "b2b.orders" },
  "b2b.payments": { path: "/b2b/payments", page: "b2b_orders/payments.php", permission: "b2b.finance" },
  "b2b.settlements": { path: "/b2b/settlements", page: "b2b_orders/settlements.php", permission: "b2b.finance" },
  "b2b.claims": { path: "/b2b/claims", page: "b2b_orders/claims.php", permission: "b2b.orders" },
  "b2b.alerts": { path: "/b2b/alerts", page: "b2b_orders/alerts.php", permission: "b2b" },
  bulk: { path: "/bulk-orders/inquiries", page: "bulk_orders/bulk_inquiry.php", permission: "bulk" },
  "bulk.warehouses": { path: "/bulk-orders/warehouses", page: "bulk_orders/warehouses.php", permission: "bulk" },
  "operations.ndr": { path: "/operations/ndr", page: "operations_center/ndr_escalations.php", permission: "operations.center" },
  "operations.escalations": { path: "/operations/escalations", page: "operations_center/ndr_escalations.php", permission: "operations.center" },
  "operations.recordings": { path: "/operations/recordings", page: "operations_center/index.php", permission: "operations.center" },
  "operations.rules": { path: "/operations/rules", page: "operations_center/settings.php", permission: "operations.rules" },
  "operations.sla": { path: "/operations/sla", page: "operations_center/settings.php", permission: "operations.rules" },
  "operations.assignments": { path: "/operations/assignments", page: "operations_team/agent_orders.php", permission: "operations.team" },
  "operations.agents": { path: "/operations/agents", page: "operations_team/agent_report.php", permission: "operations.team" },
  "operations.setup": { path: "/operations/kpi-targets", page: "operations_team/setup.php", permission: "operations.setup" },
  "cms.banners": { path: "/cms/banners", page: "newhomepage_website.php", permission: "cms" },
  "cms.homeSections": { path: "/cms/home-sections", page: "newhomepage_website.php", permission: "cms" },
  "cms.homeBanners": { path: "/cms/home-sections/banners", page: "newhomepage_website.php", permission: "cms" },
  "cms.homeSectionItems": { path: "/cms/home-sections/items", page: "newhomepage_website.php", permission: "cms" },
  "cms.pages": { path: "/custom-pages", page: "pages_custom.php", permission: "cms.pages" },
  "cms.notifications": { path: "/cms/notifications", page: "notification.php", permission: "cms.notifications" },
  ...parityLive,
  ...portLive,
};

/** PHP pages for sidebar items that are not a resource list yet. */
const EXTRA_PAGES = {
  "dashboard.main": ["dashboard.php", "main_dashboard.php"],
  "dashboard.orders": ["order_management_dashboard.php"],
  "dashboard.products": ["product_management_dashboard.php", "product_dashboard.php"],
  "dashboard.logistics": ["logistics_operations_dashboard.php"],
  "dashboard.finance": ["finance_payout_dashboard.php"],
  "dashboard.sellers": ["seller_dashboard.php"],
  "products.approval": ["verfiy_pending_products.php", "pending_products.php"],
  "products.import": ["import_products_excel.php"],
  pricing: ["price_calculator.php"],
  finance: ["finance.php", "payout_finance.php"],
  "finance.expenses": ["expense_limit_dashboard.php", "fixed_expenses.php"],
  crm: ["lead_dashboard.php", "crm_leads.php"],
  "crm.leads": ["crm_leads.php"],
  "crm.legacy": ["manager_all_leads.php", "sales_agent_leads.php"],
  "crm.whatsapp": ["whatsapp_leads.php"],
  "crm.aiCalls": ["vapi_calls.php"],
  "crm.callAudit": ["call_audit.php"],
  sales: ["sales_target_management.php"],
  "sales.targets": ["sales_target_management.php"],
  "sales.salary": ["sales_prepaid_incentive_setup.php"],
  "sales.payouts": ["sales_target_management.php"],
  roles: ["manage-role.php", "manage_roles.php"],
  "roles.menus": ["menu-master.php"],
  reports: ["reports.php", "orders_report.php"],
  settings: ["system_settings.php", "smtp_settings.php", "sms_settings.php"],
  "cms.pages": ["pages_custom.php", "meta.php"],
  "cms.notifications": ["notification.php", "notification_list.php"],
  "operations.center": ["ndr_escalations.php"],
  "support.settings": ["admin_dashboard.php"],
};

/** permission key -> PHP menu filenames that grant it. */
export function permissionPages() {
  const map = {};
  const add = (permission, page) => {
    if (!permission || !page) return;
    (map[permission] ??= new Set()).add(page);
  };
  for (const spec of Object.values(LIVE_RESOURCES)) add(spec.permission, spec.page);
  for (const [permission, pages] of Object.entries(EXTRA_PAGES)) for (const page of pages) add(permission, page);
  for (const [permission, pages] of Object.entries(parityPages)) for (const page of pages) add(permission, page);
  for (const [permission, pages] of Object.entries(portPages)) for (const page of pages) add(permission, page);
  return Object.fromEntries(Object.entries(map).map(([key, pages]) => [key, [...pages]]));
}

/** Next routes whose lists (or the order page) read the admin API. */
export const LIVE_ADMIN_PATHS = new Set([
  "/admin/dashboard",
  "/admin/dashboards/orders",
  "/admin/dashboards/products",
  "/admin/dashboards/logistics",
  "/admin/dashboards/finance",
  "/admin/dashboards/sellers",
  "/admin/finance",
  "/admin/orders",
  "/admin/orders/new",
  "/admin/products/new",
  "/admin/products/import",
  "/admin/products",
  "/admin/products/pending",
  "/admin/vendors",
  "/admin/vendors/scores",
  "/admin/vendors/verification",
  "/admin/vendors/reports",
  "/admin/customers",
  "/admin/customers/coupons",
  "/admin/customers/reviews",
  "/admin/shipping",
  "/admin/shipping/courier-slabs",
  "/admin/shipping/slabs",
  "/admin/shipping/cod-rules",
  "/admin/shipping/other-charges",
  "/admin/shipping/package-boxes",
  "/admin/shipping/weight-discrepancy",
  "/admin/shipping/pincodes",
  "/admin/returns",
  "/admin/returns/reasons",
  "/admin/refunds",
  "/admin/rto",
  "/admin/payouts",
  "/admin/payouts/items",
  "/admin/payouts/access",
  "/admin/payouts/legacy",
  "/admin/orders/invoices",
  "/admin/orders/transactions",
  "/admin/orders/whatsapp",
  "/admin/orders/sr-checkout",
  "/admin/inventory",
  "/admin/inventory/history",
  "/admin/finance/ledger",
  "/admin/finance/hold-ledger",
  "/admin/finance/cod",
  "/admin/finance/gst",
  "/admin/finance/fixed-expenses",
  "/admin/finance/wallet-withdrawals",
  "/admin/catalog/categories",
  "/admin/catalog/brands",
  "/admin/catalog/attributes",
  "/admin/catalog/tax-classes",
  "/admin/catalog/hsn-codes",
  "/admin/catalog/return-policies",
  "/admin/pricing/master-nrv",
  "/admin/pricing/commission",
  "/admin/pricing/cost-config",
  "/admin/crm",
  "/admin/crm/leads",
  "/admin/crm/follow-ups",
  "/admin/crm/legacy-leads",
  "/admin/crm/whatsapp",
  "/admin/crm/ai-calls",
  "/admin/crm/call-audit",
  "/admin/crm/circles",
  "/admin/sales",
  "/admin/sales/targets",
  "/admin/sales/salary",
  "/admin/sales/achievements",
  "/admin/sales/payouts",
  "/admin/sales/prepaid-incentive",
  "/admin/sales/team",
  "/admin/cms/blogs",
  "/admin/cms/events",
  "/admin/cms/faqs",
  "/admin/cms/footer",
  "/admin/users",
  "/admin/audit",
  "/admin/masters/geography",
  "/admin/masters/reject-reasons",
  "/admin/masters/currency",
  "/admin/settings/email-templates",
  "/admin/settings/languages",
  "/admin/support",
  "/admin/b2b/buyers",
  "/admin/b2b/rfqs",
  "/admin/b2b/quotations",
  "/admin/b2b/orders",
  "/admin/b2b/payments",
  "/admin/b2b/settlements",
  "/admin/b2b/claims",
  "/admin/b2b/alerts",
  "/admin/bulk-orders",
  "/admin/bulk-orders/warehouses",
  "/admin/operations",
  "/admin/operations/ndr",
  "/admin/operations/escalations",
  "/admin/operations/recordings",
  "/admin/operations/rules",
  "/admin/operations/sla",
  "/admin/operations/team",
  "/admin/operations/team/assignments",
  "/admin/operations/team/agents",
  "/admin/operations/team/setup",
  "/admin/cms/banners",
  "/admin/cms/home-sections",
  "/admin/cms/pages",
  "/admin/cms/notifications",
  "/admin/roles",
  "/admin/roles/menus",
  "/admin/settings",
  "/admin/settings/smtp",
  "/admin/settings/sms",
  "/admin/settings/integrations",
  "/admin/shipping/minimums",
  "/admin/finance/expense-limits",
  "/admin/pricing",
  ...parityLivePaths,
  ...portLivePaths,
]);

export function isLiveAdminPath(pathname) {
  if (LIVE_ADMIN_PATHS.has(pathname)) return true;
  const path = pathname || "";
  if (path.startsWith("/admin/dashboard/cards/")) return true;
  if (/^\/admin\/orders\/(?!new$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/crm\/leads\/\d+$/.test(path)) return true;
  if (/^\/admin\/products\/(?!new$|import$|pending$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/vendors\/(?!verification$|scores$|reports$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/vendors\/(?!verification$|scores$|reports$)[^/]+\/bank$/.test(path)) return true;
  if (/^\/admin\/customers\/(?!coupons$|reviews$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/returns\/(?!reasons$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/payouts\/(?!items$|access$|legacy$)[^/]+$/.test(path)) return true;
  if (/^\/admin\/support\/[^/]+$/.test(path)) return true;
  if (/^\/admin\/b2b\/buyers\/[^/]+$/.test(path)) return true;
  if (/^\/admin\/b2b\/orders\/[^/]+$/.test(path)) return true;
  return /^\/admin\/roles\/(?!menus$)[^/]+$/.test(path);
}
