const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Delete permanently?", description: "This cannot be undone." } };
const editAction = { id: "edit", label: "Edit", kind: "form", permission: "edit" };
const toggle = (field, on, off) => [
  { id: "enable", label: `Set ${on}`, permission: "edit", effect: { set: { [field]: on } }, when: { field, notIn: [on] } },
  { id: "disable", label: `Set ${off}`, permission: "edit", tone: "danger", effect: { set: { [field]: off } }, when: { field, in: [on] }, confirm: { title: `Set to ${off}?`, description: "Visitors will no longer see this item." } },
];

export const adminResources = {
  "cms.banners": {
    title: "Banners",
    description: "Hero and strip banners on the storefront and app, with placement, order and schedule.",
    permission: "cms",
    collection: "banners",
    api: "GET/POST /api/admin/cms/banners",
    searchFields: ["title", "placement"],
    filterFields: ["placement", "status"],
    filters: [{ key: "placement", label: "Placement", options: ["Home hero", "Home strip", "Category top"] }],
    tabs: { field: "status", values: ["Active", "Inactive"] },
    defaultSort: "order:asc",
    columns: [
      { key: "title", label: "Banner", emphasis: true, sub: "link" },
      { key: "placement", label: "Placement" },
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "startsAt", label: "Starts", type: "date" },
      { key: "endsAt", label: "Ends", type: "date" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, ...toggle("status", "Active", "Inactive"), deleteAction],
    form: {
      title: "Banner",
      fields: [
        { name: "title", label: "Title", type: "text", required: true, maxLength: 80 },
        { name: "placement", label: "Placement", type: "select", options: ["Home hero", "Home strip", "Category top"], required: true },
        { name: "link", label: "Link (path)", type: "text", required: true, pattern: "^/[a-z0-9/-]*$", patternMessage: "Use a site path like /shop/seeds." },
        { name: "order", label: "Order", type: "number", min: 1, max: 50, required: true },
        { name: "startsAt", label: "Start date", type: "date", required: true },
        { name: "endsAt", label: "End date", type: "date", required: true },
      ],
      defaults: { status: "Active" },
    },
  },
  "cms.homeSections": {
    title: "Home Sections",
    description: "Order and visibility of home page sections. The legacy “Featured categories” block never rendered on the old site.",
    permission: "cms",
    collection: "homeSections",
    api: "GET/PATCH /api/admin/cms/home-sections",
    defaultSort: "order:asc",
    columns: [
      { key: "name", label: "Section", emphasis: true },
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "items", label: "Items", type: "number" },
      { key: "status", label: "Visibility", type: "status" },
    ],
    noAdd: true,
    rowActions: [editAction],
    form: { fields: [{ name: "order", label: "Order", type: "number", min: 1, max: 20, required: true }, { name: "status", label: "Visibility", type: "select", options: ["Visible", "Hidden"], required: true }] },
  },
  "cms.blogs": {
    title: "Blogs",
    description: "Agronomy articles shown on the storefront.",
    permission: "cms",
    collection: "blogs",
    api: "GET/POST /api/admin/cms/blogs",
    search: "Search title",
    searchFields: ["title", "author"],
    filterFields: ["category", "status"],
    filters: [{ key: "category", label: "Category", options: ["Crop care", "Schemes", "Irrigation"] }],
    tabs: { field: "status", values: ["Published", "Draft"] },
    defaultSort: "publishedAt:desc",
    columns: [
      { key: "title", label: "Title", emphasis: true, width: 320 },
      { key: "author", label: "Author" },
      { key: "category", label: "Category" },
      { key: "publishedAt", label: "Date", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, ...toggle("status", "Published", "Draft"), deleteAction],
    form: {
      fields: [
        { name: "title", label: "Title", type: "text", required: true, maxLength: 120 },
        { name: "author", label: "Author", type: "text", required: true },
        { name: "category", label: "Category", type: "select", options: ["Crop care", "Schemes", "Irrigation"], required: true },
        { name: "body", label: "Body", type: "textarea", required: true },
      ],
      defaults: { status: "Draft" },
    },
  },
  "cms.events": {
    title: "Events",
    description: "Kisan melas, field demos and FPO meets.",
    permission: "cms",
    collection: "events",
    api: "GET/POST /api/admin/cms/events",
    tabs: { field: "status", values: ["Upcoming", "Completed"] },
    defaultSort: "date:desc",
    columns: [
      { key: "title", label: "Event", emphasis: true },
      { key: "city", label: "City" },
      { key: "date", label: "Date", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, deleteAction],
    form: { fields: [{ name: "title", label: "Title", type: "text", required: true }, { name: "city", label: "City", type: "text", required: true }, { name: "date", label: "Date", type: "date", required: true }], defaults: { status: "Upcoming" } },
  },
  "cms.faqs": {
    title: "FAQs",
    description: "Help-centre questions grouped by category.",
    permission: "cms",
    collection: "faqs",
    api: "GET/POST /api/admin/cms/faqs",
    search: "Search question",
    searchFields: ["question"],
    filterFields: ["category"],
    filters: [{ key: "category", label: "Category", options: ["Orders", "Payments", "Returns", "Sellers"] }],
    defaultSort: "order:asc",
    columns: [
      { key: "question", label: "Question", emphasis: true, width: 360 },
      { key: "category", label: "Category" },
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, deleteAction],
    form: {
      fields: [
        { name: "question", label: "Question", type: "text", required: true },
        { name: "answer", label: "Answer", type: "textarea", required: true },
        { name: "category", label: "Category", type: "select", options: ["Orders", "Payments", "Returns", "Sellers"], required: true },
        { name: "order", label: "Order", type: "number", min: 1, max: 100, required: true },
      ],
      defaults: { status: "Active" },
    },
  },
  "cms.pages": {
    title: "Pages",
    description: "Policy and information pages. Changes to legal pages are audited.",
    permission: "cms.pages",
    collection: "pages",
    api: "GET/PATCH /api/admin/cms/pages",
    searchFields: ["title", "slug"],
    defaultSort: "updatedAt:desc",
    columns: [
      { key: "title", label: "Page", emphasis: true, sub: "slug" },
      { key: "updatedBy", label: "Updated by" },
      { key: "updatedAt", label: "Updated", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    noAdd: true,
    rowActions: [editAction],
    form: { fields: [{ name: "title", label: "Title", type: "text", required: true }, { name: "body", label: "Content", type: "textarea", required: true }], requireReason: true },
  },
  "cms.footer": {
    title: "Footer Links",
    description: "Footer columns and links.",
    permission: "cms",
    collection: "footerLinks",
    api: "GET/POST /api/admin/cms/footer",
    filterFields: ["column"],
    filters: [{ key: "column", label: "Column", options: ["Company", "Help", "Policies", "Sell"] }],
    defaultSort: "order:asc",
    columns: [
      { key: "column", label: "Column" },
      { key: "label", label: "Label", emphasis: true },
      { key: "url", label: "URL", type: "mono" },
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, deleteAction],
    form: {
      fields: [
        { name: "column", label: "Column", type: "select", options: ["Company", "Help", "Policies", "Sell"], required: true },
        { name: "label", label: "Label", type: "text", required: true },
        { name: "url", label: "URL (path)", type: "text", required: true, pattern: "^/[a-z0-9/-]*$", patternMessage: "Use a site path like /returns." },
        { name: "order", label: "Order", type: "number", min: 1, max: 50, required: true },
      ],
      defaults: { status: "Active" },
    },
  },
  "cms.notifications": {
    title: "Push Notifications",
    description: "App push campaigns. Sending is queued on the server; the browser never holds FCM keys.",
    permission: "cms.notifications",
    collection: "pushNotifications",
    api: "POST /api/admin/notifications/push",
    tabs: { field: "status", values: ["Scheduled", "Sent"] },
    defaultSort: "sentAt:desc",
    columns: [
      { key: "title", label: "Notification", emphasis: true },
      { key: "audience", label: "Audience" },
      { key: "sentAt", label: "Sent", type: "datetime", sortable: true },
      { key: "reach", label: "Reach", type: "number" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "cancel", label: "Cancel", permission: "delete", tone: "danger", effect: { remove: true }, when: { field: "status", in: ["Scheduled"] }, confirm: { title: "Cancel scheduled notification?" } }],
    form: {
      title: "New push notification",
      fields: [
        { name: "title", label: "Title", type: "text", required: true, maxLength: 60 },
        { name: "message", label: "Message", type: "textarea", required: true, maxLength: 180 },
        { name: "audience", label: "Audience", type: "select", options: ["All app users", "Customers with orders", "Inactive 30 days"], required: true },
      ],
      defaults: { status: "Scheduled", reach: 0, sentAt: null },
      requireReason: true,
    },
  },
  users: {
    title: "Staff Users",
    description: "Admin panel accounts. Each user has exactly one role; role permissions decide what they can see and do.",
    permission: "users",
    collection: "staff",
    api: "GET/POST /api/admin/users",
    search: "Search name or email",
    searchFields: ["name", "email", "id"],
    filterFields: ["roleName", "status"],
    tabs: { field: "status", values: ["Active", "Inactive"] },
    columns: [
      { key: "name", label: "Name", emphasis: true, sub: "id" },
      { key: "email", label: "Email" },
      { key: "roleName", label: "Role" },
      { key: "status", label: "Status", type: "status" },
      { key: "lastLoginAt", label: "Last login", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "editRole", label: "Change role", kind: "form", permission: "edit" },
      { id: "deactivate", label: "Deactivate", permission: "edit", tone: "danger", effect: { set: { status: "Inactive" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Deactivate user?", description: "Their sessions stop working on the next request.", requireReason: true } },
      { id: "activate", label: "Activate", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", in: ["Inactive"] }, confirm: { title: "Re-activate user?", requireReason: true } },
    ],
    form: {
      title: "Staff user",
      fields: [
        { name: "name", label: "Full name", type: "text", required: true },
        { name: "email", label: "Work email", type: "email", required: true },
        { name: "roleId", label: "Role", type: "select", optionsFrom: "roles", required: true },
      ],
      defaults: { status: "Active", lastLoginAt: null },
      derive: "staff",
      requireReason: true,
      unique: "email",
    },
  },
  audit: {
    title: "Audit Log",
    description: "Every sensitive change made in the Admin Panel: who, what, when, from where and why. Read-only.",
    permission: "audit",
    collection: "auditLog",
    api: "GET /api/admin/audit-log",
    search: "Search actor, action or entity",
    searchFields: ["actor", "action", "entity", "reason"],
    filterFields: ["module"],
    filters: [{ key: "module", label: "Module", options: ["Auth", "Products", "Orders", "Payouts", "Refunds", "Roles", "Users", "Vendors", "Finance", "Settings", "Catalog", "Pricing", "Shipping", "CRM", "B2B", "Operations", "Support", "CMS", "Masters"] }],
    dateField: "at",
    dateRange: true,
    defaultSort: "at:desc",
    exportable: true,
    columns: [
      { key: "at", label: "When", type: "datetime", sortable: true },
      { key: "actor", label: "Actor", sub: "actorId" },
      { key: "module", label: "Module" },
      { key: "action", label: "Action", emphasis: true },
      { key: "entity", label: "Entity", type: "mono" },
      { key: "reason", label: "Reason", width: 220 },
      { key: "ip", label: "IP", type: "mono" },
    ],
  },
  "masters.geography": {
    title: "Country / State / City",
    description: "Location masters used by addresses, pincodes and shipping zones.",
    permission: "masters",
    collection: "geography",
    api: "GET/POST /api/admin/masters/geography",
    search: "Search name or code",
    searchFields: ["name", "code", "parent"],
    tabs: { field: "type", values: ["Country", "State", "City"] },
    columns: [
      { key: "name", label: "Name", emphasis: true },
      { key: "type", label: "Type" },
      { key: "parent", label: "Parent" },
      { key: "code", label: "Code", type: "mono" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, ...toggle("status", "Active", "Inactive")],
    form: {
      fields: [
        { name: "type", label: "Type", type: "select", options: ["State", "City"], required: true },
        { name: "name", label: "Name", type: "text", required: true },
        { name: "parent", label: "Parent (country/state)", type: "text", required: true },
        { name: "code", label: "Code", type: "text", required: true },
      ],
      defaults: { status: "Active" },
    },
  },
  "masters.rejectReasons": {
    title: "Reject Reasons",
    description: "Standard reasons used when rejecting products, sellers and shipments.",
    permission: "masters",
    collection: "rejectReasons",
    api: "GET/POST /api/admin/masters/reject-reasons",
    tabs: { field: "type", values: ["Product", "Seller", "Shipment"] },
    columns: [
      { key: "type", label: "Applies to" },
      { key: "reason", label: "Reason", emphasis: true, width: 360 },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [editAction, deleteAction],
    form: { fields: [{ name: "type", label: "Applies to", type: "select", options: ["Product", "Seller", "Shipment"], required: true }, { name: "reason", label: "Reason", type: "text", required: true, maxLength: 120 }], defaults: { status: "Active" } },
  },
  "masters.currency": {
    title: "Currency",
    description: "The marketplace runs in Indian Rupees only.",
    permission: "masters",
    collection: "currencies",
    api: "GET /api/admin/masters/currency",
    columns: [
      { key: "code", label: "Code", type: "mono" },
      { key: "name", label: "Name", emphasis: true },
      { key: "symbol", label: "Symbol" },
      { key: "default", label: "Default", type: "boolean" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  "settings.emailTemplates": {
    title: "Email Templates",
    description: "Transactional email templates for customers and sellers.",
    permission: "settings",
    collection: "emailTemplates",
    api: "GET/PATCH /api/admin/settings/email-templates",
    searchFields: ["name", "subject"],
    tabs: { field: "audience", values: ["Customer", "Seller"] },
    columns: [
      { key: "name", label: "Template", emphasis: true },
      { key: "subject", label: "Subject", width: 320 },
      { key: "audience", label: "Audience" },
      { key: "updatedAt", label: "Updated", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    noAdd: true,
    rowActions: [editAction],
    form: { fields: [{ name: "subject", label: "Subject", type: "text", required: true }, { name: "body", label: "Body", type: "textarea", required: true }], requireReason: true },
  },
  "settings.languages": {
    title: "Languages",
    description: "Storefront and app languages with translated phrase counts.",
    permission: "settings",
    collection: "languages",
    api: "GET/PATCH /api/admin/settings/languages",
    columns: [
      { key: "name", label: "Language", emphasis: true },
      { key: "code", label: "Code", type: "mono" },
      { key: "phrases", label: "Phrases", type: "number" },
      { key: "default", label: "Default", type: "boolean" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: toggle("status", "Active", "Inactive"),
  },
  "sales.team": {
    title: "Sales Team",
    description: "Sales executives (role 56) and managers (role 59) with circles and reporting manager.",
    permission: "sales",
    collection: "salesTeam",
    api: "GET /api/admin/sales/team",
    searchFields: ["name", "circles"],
    filterFields: ["role"],
    filters: [{ key: "role", label: "Role", options: ["Sales Executive", "Sales Manager"] }],
    columns: [
      { key: "name", label: "Name", emphasis: true, sub: "id" },
      { key: "role", label: "Role" },
      { key: "experience", label: "Experience" },
      { key: "circles", label: "Circles" },
      { key: "manager", label: "Manager" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  "operations.agents": {
    title: "Agent Performance",
    description: "Per-agent load and KPI performance for the current month.",
    permission: "operations.team",
    collection: "opsAgents",
    api: "operations_team/api/team_performance.php",
    defaultSort: "assigned:desc",
    columns: [
      { key: "name", label: "Agent", emphasis: true, sub: "id" },
      { key: "roleId", label: "Role ID", type: "number" },
      { key: "assigned", label: "Assigned lines", type: "number", sortable: true },
      { key: "confirmedPct", label: "Confirmation", type: "percent", sortable: true },
      { key: "dispatch24Pct", label: "Dispatch ≤ 24h", type: "percent", sortable: true },
      { key: "ndrResolutionPct", label: "NDR resolution", type: "percent", sortable: true },
      { key: "calls", label: "Calls", type: "number", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
  },
};
