const execs = ["Rupesh Kumar", "Anjali Verma", "Imran Khan", "Sneha Patidar", "Vivek Rathore", "Kajal Meena"];
const agents = ["Pankaj Lodhi", "Ritu Sahu", "Ashish Pawar", "Megha Tiwari"];

export const b2bOpsResources = {
  "b2b.buyers": {
    title: "Buyers / Leads",
    description: "Retailers, dealers, distributors, FPOs and institutions with segment, owner, credit and next action.",
    permission: "b2b.buyers",
    collection: "b2bBuyers",
    ownerField: "owner",
    api: "GET/POST /api/b2b/buyers",
    search: "Search firm, contact, GSTIN",
    searchFields: ["firm", "contact", "gstin", "id", "district"],
    filterFields: ["type", "segment", "owner"],
    filters: [
      { key: "type", label: "Buyer type", options: ["Retailer", "Dealer", "Distributor", "FPO", "Institution"] },
      { key: "segment", label: "Segment", options: ["B0 Lead", "B1 Qualified", "B2 Trial", "B3 Active", "B4 Repeat", "B5 High Value", "B6 Key Account"] },
      { key: "owner", label: "Owner", options: execs },
    ],
    rowHref: "/admin/b2b/buyers/{id}",
    defaultSort: "lifetimeGmv:desc",
    columns: [
      { key: "firm", label: "Buyer", sub: "id" },
      { key: "type", label: "Type" },
      { key: "district", label: "Location", sub: "state" },
      { key: "segment", label: "Segment" },
      { key: "owner", label: "Owner" },
      { key: "lifetimeGmv", label: "Lifetime GMV", type: "currency", sortable: true },
      { key: "outstanding", label: "Outstanding", type: "currency", sortable: true },
      { key: "nextFollowUp", label: "Next follow-up", type: "date", sortable: true },
    ],
    form: {
      title: "Add buyer",
      fields: [
        { name: "firm", label: "Firm name", type: "text", required: true },
        { name: "contact", label: "Contact person", type: "text", required: true },
        { name: "mobile", label: "Mobile", type: "text", required: true, pattern: "^[6-9][0-9]{9}$", patternMessage: "10-digit mobile number." },
        { name: "type", label: "Buyer type", type: "select", options: ["Retailer", "Dealer", "Distributor", "FPO", "Institution"], required: true },
        { name: "gstin", label: "GSTIN", type: "text", pattern: "^[0-9]{2}[A-Z0-9]{13}$", patternMessage: "15-character GSTIN." },
        { name: "district", label: "District", type: "text", required: true },
        { name: "state", label: "State", type: "text", required: true },
      ],
      defaults: { segment: "B0 Lead", creditLimit: 0, outstanding: 0, lifetimeGmv: 0, status: "Active" },
    },
  },
  "b2b.rfqs": {
    title: "RFQs",
    description: "Buyer requirements with a 15–30 minute quote SLA. Flow: created → seller matching → seller quotes → landed cost → commercial engine → customer quote → negotiation → PO / lost.",
    permission: "b2b.rfqs",
    collection: "rfqs",
    ownerField: "owner",
    api: "GET/POST /api/b2b/rfqs",
    search: "Search RFQ or buyer",
    searchFields: ["id", "buyer"],
    filterFields: ["status", "owner", "buyerType"],
    filters: [{ key: "owner", label: "Owner", options: execs }, { key: "buyerType", label: "Buyer type", options: ["Retailer", "Dealer", "Distributor", "FPO", "Institution"] }],
    tabs: { field: "status", values: ["Open", "Seller Sourcing", "Quotes Received", "Customer Quote Ready", "Sent", "Negotiation", "Converted", "Lost", "Expired"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "RFQ", type: "mono" },
      { key: "buyer", label: "Buyer", href: "/admin/b2b/buyers/{buyerId}", sub: "buyerType" },
      { key: "lines", label: "Lines", type: "number" },
      { key: "estValue", label: "Est. value", type: "currency", sortable: true },
      { key: "paymentMode", label: "Payment" },
      { key: "owner", label: "Owner" },
      { key: "slaDueAt", label: "Quote SLA", type: "datetime" },
      { key: "status", label: "Status", type: "status" },
      { key: "lostReason", label: "Lost reason" },
    ],
    rowActions: [
      { id: "sourcing", label: "Start seller sourcing", permission: "edit", effect: { set: { status: "Seller Sourcing" } }, when: { field: "status", in: ["Draft", "Open"] } },
      { id: "lost", label: "Mark lost", permission: "edit", tone: "danger", effect: { set: { status: "Lost" } }, when: { field: "status", notIn: ["Converted", "Lost", "Expired"] }, confirm: { title: "Mark RFQ lost?", description: "A lost reason code is mandatory (High Price, Credit, Stock, Competitor, Shipping, Delay…).", requireReason: true } },
    ],
  },
  "b2b.quotations": {
    title: "Quotations",
    description: "Commercial values come from the server engine. Quotes with expected CM below 5% or net shipping above 5% need manager approval.",
    permission: "b2b.quotations",
    headerActions: [{ label: "Create quotation", href: "/admin/b2b/quotations/new", permission: "b2b.quotations", action: "add", primary: true }],
    collection: "quotations",
    ownerField: "owner",
    api: "POST /api/b2b/quotations/{id}/recalculate|request-approval|send|convert",
    search: "Search quotation, RFQ or buyer",
    searchFields: ["id", "rfqId", "buyer"],
    filterFields: ["status", "approval", "owner"],
    filters: [{ key: "approval", label: "Approval", options: ["Approval Pending", "Auto-approved", "Approved"] }],
    tabs: { field: "status", values: ["Draft", "Approval Pending", "Approved", "Sent", "Viewed", "Negotiation", "Accepted", "Rejected", "Converted"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Quotation", type: "mono" },
      { key: "rfqId", label: "RFQ", type: "mono" },
      { key: "buyer", label: "Buyer" },
      { key: "value", label: "Value", type: "currency", sortable: true },
      { key: "takeRate", label: "Take rate", type: "percent", requires: "b2b.margin" },
      { key: "cmPercent", label: "Expected CM", type: "percent", sortable: true, requires: "b2b.margin" },
      { key: "netShippingPercent", label: "Net shipping", type: "percent" },
      { key: "approval", label: "Approval", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "validTill", label: "Valid till", type: "date" },
    ],
    rowActions: [
      { id: "approve", label: "Approve (manager)", permission: "edit", capability: "quotation.approve", effect: { set: { status: "Approved", approval: "Approved" } }, when: { field: "status", in: ["Approval Pending", "Draft"] }, confirm: { title: "Approve quotation below guard-rails?", description: "Low-CM or high-shipping approvals are audited with your reason.", requireReason: true } },
      { id: "send", label: "Send to buyer", permission: "edit", effect: { set: { status: "Sent" } }, when: { field: "status", in: ["Approved"] } },
      { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { status: "Rejected" } }, when: { field: "status", notIn: ["Converted", "Rejected"] }, confirm: { title: "Reject quotation?", requireReason: true } },
    ],
  },
  "b2b.orders": {
    title: "B2B Orders",
    description: "Order numbers BAL-B2B-xxxxx. Status: confirmed → processing → packed → dispatched → in_transit → delivered (cancel/return need a reason).",
    permission: "b2b.orders",
    collection: "b2bOrders",
    ownerField: "owner",
    api: "GET/PATCH /api/b2b/orders/{id}",
    search: "Search order, buyer or seller",
    searchFields: ["id", "buyer", "seller", "awb"],
    filterFields: ["status", "paymentStatus"],
    filters: [{ key: "paymentStatus", label: "Payment", options: ["Pending", "Partial", "Paid", "Overdue"] }],
    tabs: { field: "status", values: ["confirmed", "processing", "packed", "dispatched", "in_transit", "delivered", "returned", "cancelled"] },
    rowHref: "/admin/b2b/orders/{id}",
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "id", label: "Order", type: "mono" },
      { key: "buyer", label: "Buyer", href: "/admin/b2b/buyers/{buyerId}" },
      { key: "seller", label: "Seller", width: 200 },
      { key: "value", label: "Order value", type: "currency", sortable: true },
      { key: "contribution", label: "Contribution", type: "currency", sortable: true, requires: "b2b.margin" },
      { key: "paymentStatus", label: "Payment", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
  },
  "b2b.payments": {
    title: "Payments & Credit",
    description: "Buyer collections, credit usage and overdue payments. Sales cannot approve credit; Finance only.",
    permission: "b2b.finance",
    collection: "b2bPayments",
    api: "GET/POST /api/b2b/orders/{id}/payments · /api/b2b/credit",
    searchFields: ["id", "orderId", "buyer", "reference"],
    tabs: { field: "status", values: ["Pending", "Partial", "Paid", "Overdue"] },
    defaultSort: "dueDate:asc",
    columns: [
      { key: "id", label: "Payment", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/b2b/orders/{orderId}" },
      { key: "buyer", label: "Buyer" },
      { key: "amount", label: "Amount", type: "currency", sortable: true },
      { key: "mode", label: "Mode" },
      { key: "reference", label: "Reference", type: "mono" },
      { key: "dueDate", label: "Due", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "paid", label: "Record full payment", permission: "edit", effect: { set: { status: "Paid" } }, when: { field: "status", notIn: ["Paid"] }, confirm: { title: "Record payment as received?", description: "The server allocates the payment against the order and recalculates outstanding.", requireReason: true } }],
  },
  "b2b.settlements": {
    title: "Settlements",
    description: "Seller payable less deductions. Settlement is held while claims or disputes are open.",
    permission: "b2b.finance",
    collection: "b2bSettlements",
    api: "GET/POST /api/b2b/settlements",
    searchFields: ["id", "orderId", "seller"],
    tabs: { field: "status", values: ["Not Eligible", "Eligible", "Hold", "Processing", "Paid"] },
    columns: [
      { key: "id", label: "Settlement", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/b2b/orders/{orderId}" },
      { key: "seller", label: "Seller" },
      { key: "grossPayable", label: "Gross payable", type: "currency" },
      { key: "deductions", label: "Deductions", type: "currency" },
      { key: "netPayable", label: "Net payable", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "process", label: "Start processing", permission: "edit", effect: { set: { status: "Processing" } }, when: { field: "status", in: ["Eligible"] } },
      { id: "hold", label: "Hold", permission: "edit", effect: { set: { status: "Hold" } }, when: { field: "status", in: ["Eligible", "Processing"] }, confirm: { title: "Hold settlement?", requireReason: true } },
      { id: "paid", label: "Mark paid", permission: "edit", effect: { set: { status: "Paid" } }, when: { field: "status", in: ["Processing"] }, confirm: { title: "Mark settlement paid?", requireReason: true } },
    ],
  },
  "b2b.claims": {
    title: "Returns / Claims",
    description: "Damage, shortage and wrong-item claims with evidence and resolution.",
    permission: "b2b.orders",
    collection: "claims",
    api: "GET/POST /api/b2b/claims",
    searchFields: ["id", "orderId", "buyer"],
    filterFields: ["type", "owner"],
    filters: [{ key: "type", label: "Type", options: ["Damage", "Shortage", "Wrong item"] }],
    tabs: { field: "status", values: ["Open", "Evidence Pending", "Under Review", "Approved", "Rejected", "Settled"] },
    columns: [
      { key: "id", label: "Claim", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/b2b/orders/{orderId}" },
      { key: "buyer", label: "Buyer" },
      { key: "type", label: "Type" },
      { key: "amount", label: "Amount", type: "currency", sortable: true },
      { key: "owner", label: "Owner" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Raised", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "approve", label: "Approve claim", permission: "edit", effect: { set: { status: "Approved" } }, when: { field: "status", in: ["Open", "Evidence Pending", "Under Review"] }, confirm: { title: "Approve claim?", requireReason: true } },
      { id: "reject", label: "Reject claim", permission: "edit", tone: "danger", effect: { set: { status: "Rejected" } }, when: { field: "status", in: ["Open", "Evidence Pending", "Under Review"] }, confirm: { title: "Reject claim?", requireReason: true } },
    ],
  },
  "b2b.alerts": {
    title: "Alerts",
    description: "SLA, pricing, margin, payment and exception alerts from the B2B alert engine.",
    permission: "b2b",
    collection: "b2bAlerts",
    api: "GET/PATCH /api/b2b/alerts",
    searchFields: ["type", "entity", "assignedTo"],
    filterFields: ["severity", "type"],
    filters: [{ key: "severity", label: "Severity", options: ["High", "Medium", "Low"] }],
    tabs: { field: "status", values: ["Open", "Acknowledged", "Resolved"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "type", label: "Alert", emphasis: true, sub: "trigger" },
      { key: "severity", label: "Severity", type: "status" },
      { key: "entity", label: "Entity", type: "mono" },
      { key: "assignedTo", label: "Assigned to" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Raised", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "ack", label: "Acknowledge", permission: "view", effect: { set: { status: "Acknowledged" } }, when: { field: "status", in: ["Open"] } },
      { id: "resolve", label: "Resolve", permission: "edit", effect: { set: { status: "Resolved" } }, when: { field: "status", notIn: ["Resolved"] } },
    ],
  },
  bulk: {
    title: "Bulk Inquiries",
    description: "Older bulk-order module (legacy b2b_orders table, Shiprocket Cargo). Service charge = line total − NRV, ex-GST.",
    permission: "bulk",
    collection: "bulkInquiries",
    api: "GET /api/admin/bulk-orders/inquiries",
    search: "Search buyer, product or city",
    searchFields: ["buyer", "product", "city", "id"],
    tabs: { field: "status", values: ["New", "Quoted", "Converted", "Closed"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Inquiry", type: "mono" },
      { key: "buyer", label: "Buyer" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "product", label: "Product", width: 260 },
      { key: "quantity", label: "Quantity" },
      { key: "city", label: "City" },
      { key: "serviceCharge", label: "Service charge", type: "currency" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Received", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "quote", label: "Mark quoted", permission: "edit", effect: { set: { status: "Quoted" } }, when: { field: "status", in: ["New"] } },
      { id: "close", label: "Close", permission: "edit", tone: "danger", effect: { set: { status: "Closed" } }, when: { field: "status", notIn: ["Closed", "Converted"] }, confirm: { title: "Close inquiry?", requireReason: true } },
    ],
  },
  "bulk.warehouses": {
    title: "Warehouses",
    description: "Pickup warehouses registered for bulk / cargo shipments.",
    permission: "bulk",
    collection: "warehouses",
    api: "GET /api/admin/bulk-orders/warehouses",
    searchFields: ["name", "vendor", "city"],
    columns: [
      { key: "name", label: "Warehouse", emphasis: true },
      { key: "vendor", label: "Vendor" },
      { key: "city", label: "City" },
      { key: "pincode", label: "Pincode", type: "mono" },
      { key: "contact", label: "Contact" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  "operations.ndr": {
    title: "NDR Register",
    description: "Keyed by AWB + attempt (not invoice) so multi-vendor orders keep separate NDRs.",
    permission: "operations.center",
    headerActions: [{ label: "Escalations", href: "/admin/operations/escalations" }],
    collection: "ndr",
    ownerField: "owner",
    api: "GET/POST operations_center/api/ndr.php → /api/admin/operations/ndr",
    search: "Search order or AWB",
    searchFields: ["id", "orderId", "awb"],
    filterFields: ["courier", "owner", "status"],
    filters: [{ key: "courier", label: "Courier", options: ["NimbusPost", "Shiprocket", "Delhivery"] }, { key: "owner", label: "Agent", options: agents }],
    tabs: { field: "status", values: ["Pending", "In Progress", "Resolved"] },
    defaultSort: "raisedAt:desc",
    columns: [
      { key: "id", label: "NDR", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "awb", label: "AWB", type: "mono", sub: "courier" },
      { key: "attempt", label: "Attempt", type: "number" },
      { key: "reason", label: "NDR reason", width: 200 },
      { key: "customerResponse", label: "Customer response" },
      { key: "nextAction", label: "Next action" },
      { key: "owner", label: "Agent" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "reattempt", label: "Request reattempt", permission: "edit", effect: { set: { status: "In Progress", nextAction: "Reattempt" } }, when: { field: "status", in: ["Pending"] } },
      { id: "resolve", label: "Resolve", permission: "edit", effect: { set: { status: "Resolved" } }, when: { field: "status", notIn: ["Resolved"] }, confirm: { title: "Resolve NDR?", requireReason: true, description: "Add the resolution note for the action trail." } },
      { id: "rto", label: "Mark for RTO", permission: "edit", tone: "danger", effect: { set: { status: "Resolved", nextAction: "Mark RTO" } }, when: { field: "status", notIn: ["Resolved"] }, confirm: { title: "Mark for RTO?", description: "The parcel will return to the vendor; an RTO ledger row is written by the server.", requireReason: true } },
    ],
  },
  "operations.escalations": {
    title: "Escalations",
    description: "Raised by the 30-minute rule engine (de-duplicated) or manually. Cleared conditions auto-close.",
    permission: "operations.center",
    headerActions: [{ label: "NDR register", href: "/admin/operations/ndr" }],
    collection: "escalations",
    ownerField: "owner",
    api: "operations_center/api/escalations.php → /api/admin/operations/escalations",
    searchFields: ["id", "orderId", "rule", "title"],
    filterFields: ["severity", "owner", "source"],
    filters: [{ key: "severity", label: "Severity", options: ["High", "Medium", "Low"] }, { key: "owner", label: "Agent", options: agents }, { key: "source", label: "Source", options: ["Engine", "Manual"] }],
    tabs: { field: "status", values: ["Open", "Acknowledged", "Resolved", "Auto-Closed"] },
    defaultSort: "firstSeenAt:desc",
    columns: [
      { key: "id", label: "Escalation", type: "mono" },
      { key: "title", label: "Issue", width: 260, sub: "rule" },
      { key: "severity", label: "Severity", type: "status" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "owner", label: "Owner" },
      { key: "source", label: "Source", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "firstSeenAt", label: "First seen", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "ack", label: "Acknowledge", permission: "edit", effect: { set: { status: "Acknowledged" } }, when: { field: "status", in: ["Open"] } },
      { id: "resolve", label: "Resolve", permission: "edit", effect: { set: { status: "Resolved" } }, when: { field: "status", in: ["Open", "Acknowledged"] }, confirm: { title: "Resolve escalation?", requireReason: true } },
    ],
    bulkActions: [{ id: "ack", label: "Acknowledge", permission: "edit", effect: { set: { status: "Acknowledged" } } }],
  },
  "operations.recordings": {
    title: "Call Recordings",
    description: "Every recorded customer call from the Command Center (≤ 25 MB per file).",
    permission: "operations.center",
    collection: "recordings",
    api: "operations_center/api/calls.php?action=recordings",
    searchFields: ["id", "orderId", "agent"],
    filterFields: ["agent", "direction", "status"],
    filters: [{ key: "agent", label: "Agent", options: agents }, { key: "direction", label: "Direction", options: ["Outbound", "Inbound"] }],
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Recording", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "agent", label: "Agent" },
      { key: "direction", label: "Direction" },
      { key: "status", label: "Call status", type: "status" },
      { key: "durationSec", label: "Duration (s)", type: "number", sortable: true },
      { key: "sizeMb", label: "Size (MB)", type: "number" },
      { key: "createdAt", label: "Recorded", type: "datetime", sortable: true },
    ],
  },
  "operations.rules": {
    title: "Escalation Rules",
    description: "Thresholds read by the escalation engine on every run. Only full admins can change them.",
    permission: "operations.rules",
    headerActions: [{ label: "SLA clocks", href: "/admin/operations/sla" }],
    collection: "escalationRules",
    api: "operations_center/api/settings.php?action=save_rule",
    columns: [
      { key: "code", label: "Rule code", type: "mono" },
      { key: "description", label: "Fires when", width: 280 },
      { key: "thresholdHours", label: "Hours", type: "number" },
      { key: "thresholdCount", label: "Count", type: "number" },
      { key: "severity", label: "Severity", type: "status" },
      { key: "status", label: "Status", type: "status" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit threshold", kind: "form", permission: "edit" }],
    form: {
      fields: [
        { name: "thresholdHours", label: "Threshold hours", type: "number", min: 0, max: 720 },
        { name: "thresholdCount", label: "Threshold count", type: "number", min: 0, max: 20 },
        { name: "severity", label: "Severity", type: "select", options: ["High", "Medium", "Low"], required: true },
      ],
      requireReason: true,
    },
  },
  "operations.sla": {
    title: "SLA Clocks",
    description: "Stage SLA in hours. Tracker shows “at risk” at the warn % and “breached” past the clock.",
    permission: "operations.rules",
    headerActions: [{ label: "Escalation rules", href: "/admin/operations/rules" }],
    collection: "slaConfig",
    api: "operations_center/api/settings.php?action=save_sla",
    columns: [
      { key: "name", label: "Stage", emphasis: true, sub: "code" },
      { key: "slaHours", label: "SLA (hours)", type: "number" },
      { key: "warnPercent", label: "Warn at", type: "percent" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: { fields: [{ name: "slaHours", label: "SLA hours", type: "number", min: 1, max: 720, required: true }, { name: "warnPercent", label: "Warn at %", type: "number", min: 50, max: 99, required: true }], requireReason: true },
  },
  "operations.assignments": {
    title: "Order Assignment",
    description: "Order lines (order + invoice grain) assigned to operations agents. Auto-assign gives work to the least-loaded agent.",
    permission: "operations.team",
    collection: "opsTracker",
    ownerField: "agent",
    api: "operations_team/api/assign_orders.php → /api/admin/operations/assignments",
    search: "Search order, invoice or vendor",
    searchFields: ["orderId", "invoice", "vendor", "customer", "awb"],
    filterFields: ["agent", "stage", "slaState"],
    filters: [
      { key: "agent", label: "Agent", options: agents },
      { key: "slaState", label: "SLA", options: ["On track", "At risk", "Breached"] },
    ],
    tabs: { field: "stage", values: ["pending", "processing", "packed", "shipped", "ndr", "rto", "delivered", "cancelled"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "invoice", label: "Invoice", type: "mono" },
      { key: "vendor", label: "Vendor", width: 180 },
      { key: "customer", label: "Customer" },
      { key: "status", label: "Line status", type: "status" },
      { key: "agent", label: "Agent" },
      { key: "slaState", label: "SLA", type: "status" },
      { key: "value", label: "Value", type: "currency", sortable: true },
      { key: "createdAt", label: "Placed", type: "datetime", sortable: true },
    ],
    bulkActions: [{ id: "assign", label: "Assign to agent…", permission: "edit", assign: { field: "agent", label: "Assign to agent", options: agents }, confirm: { title: "Assign selected order lines?", description: "The agent sees these lines in their queue." } }],
  },
  "operations.setup": {
    title: "Agents & KPI Targets",
    description: "Agent master (role IDs 32, 57, 66) and KPI targets / KRI thresholds.",
    permission: "operations.setup",
    collection: "kpiTargets",
    api: "operations_team/setup → /api/admin/operations/kpi-targets",
    columns: [
      { key: "name", label: "KPI", emphasis: true },
      { key: "target", label: "Target", type: "percent" },
      { key: "kri", label: "KRI threshold", type: "percent" },
      { key: "actual", label: "Actual (MTD)", type: "percent" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: { fields: [{ name: "target", label: "Target %", type: "number", min: 0, max: 100, required: true }, { name: "kri", label: "KRI threshold %", type: "number", min: 0, max: 100, required: true }], requireReason: true },
  },
  "support.sla": {
    title: "Departments & SLA",
    description: "Ticket SLA by priority and category, and the owning department.",
    permission: "support.settings",
    collection: "supportSla",
    api: "GET/PATCH /api/admin/support/sla",
    columns: [
      { key: "rule", label: "Rule", emphasis: true },
      { key: "department", label: "Department" },
      { key: "slaHours", label: "SLA (hours)", type: "number" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: { fields: [{ name: "department", label: "Department", type: "select", options: ["Vendor Support", "Logistics", "Finance", "Tech", "All"], required: true }, { name: "slaHours", label: "SLA hours", type: "number", min: 1, max: 240, required: true }], requireReason: true },
  },
};
