const activeToggle = [
  { id: "activate", label: "Activate", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", notIn: ["Active"] } },
  { id: "deactivate", label: "Deactivate", permission: "edit", tone: "danger", effect: { set: { status: "Inactive" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Deactivate record?", description: "It will be hidden from the storefront and seller panel." } },
];
const approvalActions = [
  { id: "approve", label: "Approve", permission: "edit", effect: { set: { approval: "Approved", status: "Active" } }, when: { field: "approval", in: ["Pending"] } },
  { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { approval: "Rejected", status: "Inactive" } }, when: { field: "approval", in: ["Pending"] }, confirm: { title: "Reject request?", description: "The seller who requested it will be notified.", requireReason: true } },
];
const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Delete permanently?", description: "This cannot be undone." } };
const statusOptions = ["Active", "Inactive"];

export const catalogResources = {
  "catalog.categories": {
    title: "Categories",
    description: "Two-level agriculture category tree. Sellers can request new categories; requests appear as Pending.",
    permission: "catalog.categories",
    collection: "categories",
    api: "GET /api/admin/catalog/categories",
    search: "Search category",
    searchFields: ["name", "parent"],
    filterFields: ["level", "approval", "status"],
    filters: [
      { key: "level", label: "Level", options: [{ value: "1", label: "Parent" }, { value: "2", label: "Sub-category" }] },
      { key: "approval", label: "Approval", options: ["Approved", "Pending", "Rejected"] },
    ],
    tabs: { field: "approval", values: ["Approved", "Pending", "Rejected"] },
    defaultSort: "id:asc",
    columns: [
      { key: "name", label: "Category", sortable: true, emphasis: true, sub: "parent" },
      { key: "level", label: "Level", sortable: true },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "approval", label: "Approval", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...approvalActions, ...activeToggle, deleteAction],
    bulkActions: [approvalActions[0], activeToggle[1]],
    form: {
      fields: [
        { name: "name", label: "Category name", type: "text", required: true, maxLength: 80 },
        { name: "parent", label: "Parent category", type: "text", hint: "Leave blank for a top-level category." },
        { name: "status", label: "Status", type: "select", options: statusOptions, required: true },
      ],
      defaults: { status: "Active", approval: "Approved", products: 0, level: 1 },
    },
  },
  "catalog.brands": {
    title: "Brands",
    description: "Brand master with SEO slug. Seller-requested brands wait in the approval queue.",
    permission: "catalog.brands",
    collection: "brands",
    api: "GET /api/admin/catalog/brands",
    search: "Search brand",
    searchFields: ["name", "slug"],
    filterFields: ["approval", "status"],
    filters: [{ key: "status", label: "Status", options: statusOptions }],
    tabs: { field: "approval", values: ["Approved", "Pending", "Rejected"] },
    defaultSort: "products:desc",
    columns: [
      { key: "name", label: "Brand", sortable: true, emphasis: true, sub: "slug" },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "seoTitle", label: "SEO title", width: 260 },
      { key: "approval", label: "Approval", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...approvalActions, ...activeToggle, deleteAction],
    bulkActions: [approvalActions[0]],
    form: {
      fields: [
        { name: "name", label: "Brand name", type: "text", required: true, maxLength: 60 },
        { name: "slug", label: "URL slug", type: "text", required: true, pattern: "^[a-z0-9-]+$", patternMessage: "Use lowercase letters, numbers and hyphens." },
        { name: "seoTitle", label: "SEO title", type: "text", maxLength: 70 },
        { name: "status", label: "Status", type: "select", options: statusOptions, required: true },
      ],
      defaults: { status: "Active", approval: "Approved", products: 0 },
    },
  },
  "catalog.attributes": {
    title: "Attributes",
    description: "Attributes, attribute values and attribute sets used for product variants (pack size, weight, formulation).",
    permission: "catalog.attributes",
    collection: "attributes",
    api: "GET /api/admin/catalog/attributes",
    search: "Search attribute",
    searchFields: ["name", "values", "set"],
    filterFields: ["type", "approval"],
    filters: [{ key: "type", label: "Type", options: ["Select", "Text", "Number"] }],
    tabs: { field: "approval", values: ["Approved", "Pending"] },
    defaultSort: "id:asc",
    columns: [
      { key: "name", label: "Attribute", emphasis: true, sortable: true },
      { key: "type", label: "Type" },
      { key: "values", label: "Values", width: 320 },
      { key: "set", label: "Attribute set" },
      { key: "approval", label: "Approval", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...approvalActions, deleteAction],
    form: {
      fields: [
        { name: "name", label: "Attribute name", type: "text", required: true },
        { name: "type", label: "Input type", type: "select", options: ["Select", "Text", "Number"], required: true },
        { name: "values", label: "Values (comma separated)", type: "textarea" },
        { name: "set", label: "Attribute set", type: "text" },
      ],
      defaults: { approval: "Approved" },
    },
  },
  "catalog.tax": {
    title: "Tax Classes",
    description: "GST slabs applied to products. GST is inclusive in the selling price.",
    permission: "catalog.tax",
    collection: "taxClasses",
    api: "GET /api/admin/catalog/tax-classes",
    searchFields: ["name"],
    filterFields: ["approval"],
    defaultSort: "rate:asc",
    columns: [
      { key: "name", label: "Tax class", emphasis: true },
      { key: "rate", label: "GST %", type: "percent", sortable: true },
      { key: "products", label: "Products", type: "number" },
      { key: "approval", label: "Approval", type: "status" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...approvalActions, ...activeToggle],
    form: {
      fields: [
        { name: "name", label: "Name", type: "text", required: true },
        { name: "rate", label: "GST %", type: "number", required: true, min: 0, max: 28 },
        { name: "status", label: "Status", type: "select", options: statusOptions, required: true },
      ],
      defaults: { status: "Active", approval: "Approved", products: 0 },
    },
  },
  "catalog.hsn": {
    title: "HSN Codes",
    description: "HSN codes used on invoices and GST returns.",
    permission: "catalog.hsn",
    collection: "hsnCodes",
    api: "GET /api/admin/catalog/hsn-codes",
    search: "Search HSN code or description",
    searchFields: ["code", "description"],
    defaultSort: "code:asc",
    columns: [
      { key: "code", label: "HSN code", type: "mono", sortable: true },
      { key: "description", label: "Description", width: 360 },
      { key: "gst", label: "GST %", type: "percent" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      fields: [
        { name: "code", label: "HSN code", type: "text", required: true, pattern: "^[0-9]{4,8}$", patternMessage: "4–8 digits." },
        { name: "description", label: "Description", type: "text", required: true },
        { name: "gst", label: "GST %", type: "number", min: 0, max: 28, required: true },
      ],
      defaults: { status: "Active" },
    },
  },
  "catalog.returnPolicies": {
    title: "Return Policies",
    description: "Return windows used to set `return_last_date` on each order line at checkout.",
    permission: "catalog.returnPolicies",
    collection: "returnPolicies",
    api: "GET /api/admin/catalog/return-policies",
    searchFields: ["name"],
    filterFields: ["approval"],
    tabs: { field: "approval", values: ["Approved", "Pending"] },
    defaultSort: "validityDays:asc",
    columns: [
      { key: "name", label: "Policy", emphasis: true },
      { key: "type", label: "Type" },
      { key: "validityDays", label: "Validity (days)", type: "number", sortable: true },
      { key: "refundAllowed", label: "Refund allowed", type: "boolean" },
      { key: "approval", label: "Approval", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...approvalActions, deleteAction],
    form: {
      fields: [
        { name: "name", label: "Policy name", type: "text", required: true },
        { name: "type", label: "Type", type: "select", options: ["Refund", "Replacement", "No return"], required: true },
        { name: "validityDays", label: "Validity (days)", type: "number", min: 0, max: 60, required: true },
      ],
      defaults: { approval: "Approved", refundAllowed: true },
    },
  },
  "pricing.masterNrv": {
    title: "Master NRV",
    description: "Net receivable values imported from the master sheet. Selling prices are derived from NRV on the server.",
    permission: "pricing.masterNrv",
    collection: "masterNrv",
    api: "GET /api/admin/pricing/master-nrv · POST /api/admin/pricing/master-nrv/import",
    search: "Search SKU, product or vendor",
    searchFields: ["sku", "product", "vendor"],
    defaultSort: "effectiveFrom:desc",
    dateField: "effectiveFrom",
    exportable: true,
    columns: [
      { key: "sku", label: "SKU", type: "mono", sortable: true },
      { key: "product", label: "Product", width: 300, emphasis: true, sub: "vendor" },
      { key: "nrv", label: "NRV", type: "currency", sortable: true },
      { key: "mrp", label: "MRP", type: "currency", sortable: true },
      { key: "effectiveFrom", label: "Effective from", type: "date", sortable: true },
      { key: "uploadedBy", label: "Uploaded by" },
    ],
    rowActions: [{ id: "edit", label: "Edit NRV", kind: "form", permission: "edit", sensitive: true }],
    form: {
      fields: [
        { name: "nrv", label: "NRV (₹)", type: "number", required: true, min: 1 },
        { name: "mrp", label: "MRP (₹)", type: "number", required: true, min: 301 },
      ],
      requireReason: true,
    },
  },
  "pricing.commission": {
    title: "Seller Commission",
    description: "Price-range commission rules. Seller-specific beats general; exact category beats list; if ad + office + profit > 0 the commission is their sum.",
    permission: "pricing.commission",
    collection: "commissionRules",
    api: "GET /api/admin/pricing/commission-rules",
    search: "Search category or seller",
    searchFields: ["category", "seller"],
    filterFields: ["seller"],
    defaultSort: "priceFrom:asc",
    columns: [
      { key: "priceFrom", label: "Price from", type: "currency", sortable: true },
      { key: "priceTo", label: "Price to", type: "currency" },
      { key: "category", label: "Category" },
      { key: "seller", label: "Seller" },
      { key: "commission", label: "Commission %", type: "percent", sortable: true },
      { key: "adExpense", label: "Ad %", type: "percent" },
      { key: "officeExpense", label: "Office %", type: "percent" },
      { key: "profit", label: "Profit %", type: "percent" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      fields: [
        { name: "priceFrom", label: "Price from (₹)", type: "number", required: true, min: 0 },
        { name: "priceTo", label: "Price to (₹)", type: "number", required: true, min: 1 },
        { name: "category", label: "Category", type: "text", required: true },
        { name: "seller", label: "Seller (blank = General)", type: "text" },
        { name: "commission", label: "Commission %", type: "number", required: true, min: 0, max: 60 },
        { name: "adExpense", label: "Ad expense %", type: "number", min: 0, max: 30 },
        { name: "officeExpense", label: "Office expense %", type: "number", min: 0, max: 30 },
        { name: "profit", label: "Profit %", type: "number", min: 0, max: 40 },
      ],
      defaults: { status: "Active", seller: "General", adExpense: 0, officeExpense: 0, profit: 0 },
      requireReason: true,
    },
  },
  "pricing.costConfig": {
    title: "Listing Economics",
    description: "Contribution guard-rails resolved product → seller → category → global. Listings below floor only show a warning.",
    permission: "pricing.costConfig",
    collection: "costConfig",
    api: "GET /api/admin/pricing/cost-config",
    searchFields: ["target", "scope"],
    filterFields: ["scope"],
    filters: [{ key: "scope", label: "Scope", options: ["Global", "Category", "Seller", "Product"] }],
    columns: [
      { key: "scope", label: "Scope", type: "status" },
      { key: "target", label: "Applies to", emphasis: true },
      { key: "takeRateMin", label: "Take rate min", type: "percent" },
      { key: "takeRateMax", label: "Take rate max", type: "percent" },
      { key: "floorPct", label: "Floor CM", type: "percent" },
      { key: "targetPct", label: "Target CM", type: "percent" },
      { key: "marketingPct", label: "Marketing", type: "percent" },
      { key: "packagingPct", label: "Packaging", type: "percent" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: {
      fields: [
        { name: "takeRateMin", label: "Take rate min %", type: "number", min: 25, max: 45, required: true },
        { name: "takeRateMax", label: "Take rate max %", type: "number", min: 25, max: 45, required: true },
        { name: "floorPct", label: "Floor contribution %", type: "number", min: 0, max: 30, required: true },
        { name: "targetPct", label: "Target contribution %", type: "number", min: 0, max: 30, required: true },
      ],
      requireReason: true,
    },
  },
};
