const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Are you sure want to delete?", description: "This cannot be undone." } };
const masterStatus = ["Pending", "Active", "Deactive"];
const IMAGE = "image/png,image/jpeg,image/jpg,image/gif,image/webp";

/**
 * Catalog masters, column for column as the PHP pages:
 * category.php, brand.php, manage_conf_attributes.php, manage_tax_class.php,
 * manage_hsncode.php and manage_return_policy.php.
 */
export const catalogResources = {
  "catalog.categories": {
    title: "Category",
    description: "One level at a time: View sub category opens the children. Categories with products are deleted after moving their products to another category.",
    permission: "catalog.categories",
    search: "Search category",
    searchFields: ["name", "slug"],
    defaultSort: "order:asc",
    headerActions: [{ href: "/admin/catalog/categories/pending", label: "Pending Category" }],
    columns: [
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "image", label: "Image", type: "image" },
      { key: "name", label: "Category", sortable: true, emphasis: true, sub: "slug" },
      { key: "status", label: "Status", type: "status" },
      { key: "children", label: "Sub categories", type: "number" },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "commissionFees", label: "Commission %", type: "number", hidden: true },
      { key: "gst", label: "GST %", type: "number", hidden: true },
      { key: "createdAt", label: "Created", type: "date", hidden: true },
    ],
    rowActions: [
      { id: "children", label: "View sub category", permission: "view", href: "/admin/catalog/categories?parentId={id}", when: { field: "children", notIn: [0] } },
      { id: "commission", label: "Commission (Add/View)", permission: "view", href: "/admin/catalog/category-commission?categoryId={id}" },
      { id: "timeline", label: "View History", permission: "view", href: "/admin/catalog/categories/timeline?categoryId={id}" },
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { ...deleteAction, when: { field: "products", in: [0] } },
      {
        id: "reassign",
        label: "Assign products & delete",
        permission: "delete",
        tone: "danger",
        when: { field: "products", notIn: [0] },
        assign: { label: "Assign the products to", optionsFrom: "lookup:categories", run: true },
        confirm: { title: "Assign Category", description: "This category has products. Choose the category they move to; then it is deleted." },
      },
    ],
    form: {
      title: "Category",
      fields: [
        { name: "parentId", label: "Parent category", type: "select", optionsFrom: "lookup:categories", options: [{ value: "0", label: "— Make it a parent category —" }], fromQuery: "parentId", default: "0", required: true, only: "new" },
        { name: "order", label: "Order", type: "number", min: 0, only: "edit" },
        { name: "name", label: "Category Name", type: "text", required: true, maxLength: 80 },
        { name: "commissionFees", label: "Commission", type: "number", min: 0, max: 100 },
        { name: "gst", label: "GST", type: "number", min: 0, max: 100 },
        { name: "status", label: "Status", type: "select", options: ["Active", "Inactive", "Pending"], required: true, only: "edit" },
        { name: "image", label: "Image", type: "file", accept: IMAGE, maxBytes: 5 * 1024 * 1024 },
        { name: "adImage", label: "Advertisement Image", type: "file", accept: IMAGE, maxBytes: 5 * 1024 * 1024, only: "edit" },
        { name: "adLink", label: "Advertisement Link", type: "text", maxLength: 500, only: "edit" },
        { name: "metaTitle", label: "Meta Title", type: "text", maxLength: 500 },
        { name: "metaDescription", label: "Meta Description", type: "text", maxLength: 2000 },
        { name: "metaKeywords", label: "Meta Keywords", type: "text", maxLength: 2000 },
        { name: "pageDescription", label: "Page Description", type: "html" },
      ],
    },
  },
  "catalog.brands": {
    title: "Brand",
    description: "Brands with SEO details. Brands used by products are deleted after moving their products to another brand.",
    permission: "catalog.brands",
    search: "Search brand",
    searchFields: ["name", "slug"],
    tabs: { field: "status", values: ["Active", "Deactive"] },
    filters: [{ key: "popularLabel", label: "Popular", options: ["Yes", "No"] }],
    defaultSort: "name:asc",
    headerActions: [{ href: "/admin/catalog/brands/pending", label: "Pending Brand" }],
    columns: [
      { key: "order", label: "Order", type: "number", sortable: true },
      { key: "image", label: "Image", type: "image" },
      { key: "name", label: "Brand Name", sortable: true, emphasis: true, sub: "slug" },
      { key: "status", label: "Status", type: "status" },
      { key: "popular", label: "Popular", type: "boolean" },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "siteUrl", label: "Website", hidden: true },
      { key: "metaTitle", label: "Meta Title", hidden: true },
    ],
    rowActions: [
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { ...deleteAction, when: { field: "products", in: [0] } },
      {
        id: "reassign",
        label: "Assign products & delete",
        permission: "delete",
        tone: "danger",
        when: { field: "products", notIn: [0] },
        assign: { label: "Assign the products to", optionsFrom: "lookup:brands", run: true },
        confirm: { title: "Assign Brand", description: "This brand is used by products. Choose the brand they move to; then it is deleted." },
      },
    ],
    form: {
      title: "Brand",
      fields: [
        { name: "order", label: "Order", type: "number", min: 0, only: "edit" },
        { name: "name", label: "Brand Name", type: "text", required: true, maxLength: 100 },
        { name: "nameAr", label: "Brand Name (Arabic)", type: "text", maxLength: 100 },
        { name: "siteUrl", label: "Website Link", type: "text", maxLength: 255 },
        { name: "status", label: "Status", type: "select", options: masterStatus, required: true, only: "edit" },
        { name: "popular", label: "Popular Brand", type: "checkbox" },
        { name: "image", label: "Brand Image", type: "file", accept: IMAGE, maxBytes: 5 * 1024 * 1024, required: true },
        { name: "slug", label: "Brand Slug (URL)", type: "text", maxLength: 255, hint: "Leave empty to build it from the name." },
        { name: "description", label: "Brand Description", type: "textarea", rows: 5, maxLength: 20000 },
        { name: "metaTitle", label: "Meta Title", type: "text", maxLength: 255 },
        { name: "metaDescription", label: "Meta Description", type: "textarea", rows: 3, maxLength: 5000 },
        { name: "metaKeywords", label: "Meta Keywords", type: "text", maxLength: 2000 },
        { name: "manufacturingLocation", label: "Manufacturing Location", type: "text", maxLength: 255 },
        { name: "certifications", label: "Certifications", type: "textarea", rows: 3, maxLength: 5000 },
        { name: "cropsCovered", label: "Crops Covered", type: "textarea", rows: 3, maxLength: 5000 },
        { name: "whyChoose", label: "Why Choose This Brand", type: "textarea", rows: 4, maxLength: 5000 },
      ],
    },
  },
  "catalog.attributes": {
    title: "Configuration Attributes",
    description: "Attributes used for product variants. View lists an attribute's values.",
    permission: "catalog.attributes",
    search: "Search attribute",
    searchFields: ["name", "values"],
    tabs: { field: "status", values: ["Pending", "Active"] },
    defaultSort: "name:asc",
    headerActions: [
      { href: "/admin/catalog/attributes/pending", label: "Pending Attributes" },
      { href: "/admin/catalog/attribute-sets/pending", label: "Pending Attribute Sets" },
    ],
    columns: [
      { key: "name", label: "Attributes", emphasis: true, sortable: true },
      { key: "values", label: "Values", wrap: true, width: 320 },
      { key: "valueCount", label: "No. of values", type: "number", sortable: true },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "values", label: "View", permission: "view", href: "/admin/catalog/attribute-values?attributeId={id}" },
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { id: "approve", label: "Approve", permission: "edit", effect: { run: "approve" }, when: { field: "status", in: ["Pending"] } },
      deleteAction,
    ],
    form: {
      title: "Attribute",
      fields: [
        { name: "name", label: "Attributes", type: "text", required: true, maxLength: 200 },
        { name: "nameAr", label: "Attributes (Arabic)", type: "text", maxLength: 255 },
      ],
    },
  },
  "catalog.tax": {
    title: "Tax Class",
    description: "Active and deactivated tax classes. Seller requests wait under Pending Tax Class.",
    permission: "catalog.tax",
    search: "Search tax label",
    searchFields: ["name"],
    tabs: { field: "status", values: ["Active", "Deactive"] },
    defaultSort: "rate:asc",
    headerActions: [{ href: "/admin/catalog/tax-classes/pending", label: "Pending Tax Class" }],
    columns: [
      { key: "name", label: "Tax Label", emphasis: true, sortable: true },
      { key: "rate", label: "Tax Class (%)", type: "number", sortable: true },
      { key: "products", label: "Seller offers", type: "number" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { ...deleteAction, confirm: { title: "Delete this tax class?", description: "Seller offers using it are reset to no tax class." } },
    ],
    form: {
      title: "Tax Class",
      fields: [
        { name: "name", label: "Tax Label", type: "text", required: true, maxLength: 50 },
        { name: "rate", label: "Tax Class (%)", type: "number", required: true, min: 0, max: 100 },
        { name: "status", label: "Status", type: "select", options: masterStatus, required: true, only: "edit" },
      ],
    },
  },
  "catalog.hsn": {
    title: "HSN Code",
    description: "HSN codes sellers can pick. A code used by a product cannot be deleted.",
    permission: "catalog.hsn",
    search: "Search HSN code",
    searchFields: ["code"],
    defaultSort: "id:asc",
    columns: [
      { key: "code", label: "HSN Code", type: "mono", sortable: true, emphasis: true },
      { key: "products", label: "Products", type: "number" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      title: "HSN Code",
      fields: [{ name: "code", label: "HSN Code", type: "text", required: true, pattern: "^[0-9]+$", patternMessage: "Digits only." }],
    },
  },
  "catalog.returnPolicies": {
    title: "Return Policy",
    description: "Active and deactivated return policies. Seller requests wait under Pending Return Policy.",
    permission: "catalog.returnPolicies",
    search: "Search policy",
    searchFields: ["name", "policy"],
    tabs: { field: "status", values: ["Active", "Deactive"] },
    defaultSort: "name:asc",
    headerActions: [{ href: "/admin/catalog/return-policies/pending", label: "Pending Return Policy" }],
    columns: [
      { key: "name", label: "Return Policy", emphasis: true, sortable: true },
      { key: "validityDays", label: "Validity(Days)", type: "number", sortable: true },
      { key: "type", label: "Type Accepted" },
      { key: "products", label: "Products", type: "number" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { ...deleteAction, confirm: { title: "Delete this return policy?", description: "Products using it are left without a return policy." } },
    ],
    form: {
      title: "Return Policy",
      fields: [
        { name: "name", label: "Policy title", type: "text", required: true, maxLength: 500 },
        { name: "validityDays", label: "Validity(Days)", type: "number", required: true, min: 0, max: 3650 },
        { name: "refundAllowed", label: "Refund", type: "checkbox" },
        { name: "replaceAllowed", label: "Replace", type: "checkbox" },
        { name: "exchangeAllowed", label: "Exchange", type: "checkbox" },
        { name: "status", label: "Status", type: "select", options: masterStatus, required: true, only: "edit" },
        { name: "policy", label: "Policy content", type: "html" },
      ],
    },
  },
  "pricing.masterNrv": {
    title: "Master NRV",
    description: "Net receivable values imported from the master sheet. Selling prices are derived from NRV on the server.",
    permission: "pricing.masterNrv",
    collection: "masterNrv",
    api: "GET /api/admin/pricing/master-nrv · POST /api/admin/pricing/master-nrv/import",
    search: "Search SKU, product or vendor",
    searchFields: ["sku", "product", "vendor"],
    defaultSort: "effectiveFrom:desc",
    dateField: "effectiveFrom",
    exportable: true,
    columns: [
      { key: "sku", label: "SKU", type: "mono", sortable: true },
      { key: "product", label: "Product", width: 300, emphasis: true, sub: "vendor" },
      { key: "nrv", label: "NRV", type: "currency", sortable: true },
      { key: "mrp", label: "MRP", type: "currency", sortable: true },
      { key: "effectiveFrom", label: "Effective from", type: "date", sortable: true },
      { key: "uploadedBy", label: "Uploaded by" },
    ],
    rowActions: [{ id: "edit", label: "Edit NRV", kind: "form", permission: "edit", sensitive: true }],
    form: {
      fields: [
        { name: "nrv", label: "NRV (₹)", type: "number", required: true, min: 1 },
        { name: "mrp", label: "MRP (₹)", type: "number", required: true, min: 301 },
      ],
      requireReason: true,
    },
  },
  "pricing.commission": {
    title: "Seller Commission",
    description: "Price-range commission rules. Seller-specific beats general; exact category beats list; if ad + office + profit > 0 the commission is their sum.",
    permission: "pricing.commission",
    collection: "commissionRules",
    api: "GET /api/admin/pricing/commission-rules",
    search: "Search category or seller",
    searchFields: ["category", "seller"],
    filterFields: ["seller"],
    defaultSort: "priceFrom:asc",
    columns: [
      { key: "priceFrom", label: "Price from", type: "currency", sortable: true },
      { key: "priceTo", label: "Price to", type: "currency" },
      { key: "category", label: "Category" },
      { key: "seller", label: "Seller" },
      { key: "commission", label: "Commission %", type: "percent", sortable: true },
      { key: "adExpense", label: "Ad %", type: "percent" },
      { key: "officeExpense", label: "Office %", type: "percent" },
      { key: "profit", label: "Profit %", type: "percent" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      fields: [
        { name: "priceFrom", label: "Price from (₹)", type: "number", required: true, min: 0 },
        { name: "priceTo", label: "Price to (₹)", type: "number", required: true, min: 1 },
        { name: "category", label: "Category", type: "text", required: true },
        { name: "seller", label: "Seller (blank = General)", type: "text" },
        { name: "commission", label: "Commission %", type: "number", required: true, min: 0, max: 60 },
        { name: "adExpense", label: "Ad expense %", type: "number", min: 0, max: 30 },
        { name: "officeExpense", label: "Office expense %", type: "number", min: 0, max: 30 },
        { name: "profit", label: "Profit %", type: "number", min: 0, max: 40 },
      ],
      defaults: { status: "Active", seller: "General", adExpense: 0, officeExpense: 0, profit: 0 },
      requireReason: true,
    },
  },
  "pricing.costConfig": {
    title: "Listing Economics",
    description: "Contribution guard-rails resolved product → seller → category → global. Listings below floor only show a warning.",
    permission: "pricing.costConfig",
    collection: "costConfig",
    api: "GET /api/admin/pricing/cost-config",
    searchFields: ["target", "scope"],
    filterFields: ["scope"],
    filters: [{ key: "scope", label: "Scope", options: ["Global", "Category", "Seller", "Product"] }],
    columns: [
      { key: "scope", label: "Scope", type: "status" },
      { key: "target", label: "Applies to", emphasis: true },
      { key: "takeRateMin", label: "Take rate min", type: "percent" },
      { key: "takeRateMax", label: "Take rate max", type: "percent" },
      { key: "floorPct", label: "Floor CM", type: "percent" },
      { key: "targetPct", label: "Target CM", type: "percent" },
      { key: "marketingPct", label: "Marketing", type: "percent" },
      { key: "packagingPct", label: "Packaging", type: "percent" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: {
      fields: [
        { name: "takeRateMin", label: "Take rate min %", type: "number", min: 25, max: 45, required: true },
        { name: "takeRateMax", label: "Take rate max %", type: "number", min: 25, max: 45, required: true },
        { name: "floorPct", label: "Floor contribution %", type: "number", min: 0, max: 30, required: true },
        { name: "targetPct", label: "Target contribution %", type: "number", min: 0, max: 30, required: true },
      ],
      requireReason: true,
    },
  },
};
