import { NOW } from "@/lib/mock/admin/seed";

/** manage_orders.php status tabs. "Pickup" is every pickup or manifested line; the rest match a line status that contains the word. */
const orderStatuses = [
  "Placed",
  "Accepted",
  { value: "Pickup", label: "Pending pickup" },
  "Rejected",
  "Packed",
  "Shipped",
  "In Transit",
  "Out for Delivery",
  "Delivered",
  "Undelivered",
  "RTO",
  "RTO Delivered",
  { value: "Return", label: "Return" },
  "Return Completed",
  "Cancelled",
];
const manualStatuses = [
  "Placed", "Accepted", "Rejected", "Packed", "Ready To Ship", "Manifested",
  "Pending Pickup", "Pickup Scheduled", "Pickup Generated", "Pickup Exception",
  "Picked Up", "Shipped", "In Transit", "Dispatched", "Out for Delivery",
  "Delivered", "Undelivered", "RTO", "Cancelled",
  "Return Accepted", "Return Cancelled", "Return Completed",
];
const responsibleParties = [
  { value: "user", label: "User / Customer" },
  { value: "vendor", label: "Vendor / Seller" },
  { value: "operation", label: "Operation / Admin" },
  { value: "courier", label: "Courier" },
];
const couriers = ["NimbusPost", "Shiprocket", "Delhivery"];
const categories = ["Seeds", "Fertilizers", "Crop Protection", "Irrigation", "Farm Equipment", "Garden"];
const verdictLabels = { ok: "Healthy", below_target: "Below target CM", below_floor: "Below floor CM", loss: "Loss-making" };

export const coreResources = {
  orders: {
    title: "All Orders",
    description: "One row per order. The status is the furthest line along delivery. Line status is each seller invoice, and remarks lists every note. The status filter matches a product line the same way the PHP tabs do.",
    permission: "orders",
    collection: "orders",
    api: "GET /api/admin/orders",
    search: "Search order, customer, product, invoice or AWB",
    searchFields: ["id", "customer", "mobile", "email", "platformInvoice", "invoiceNumber", "paymentId", "productName", "trackingId"],
    filterFields: ["status", "paymentMode", "channel", "dateOn"],
    filters: [
      { key: "status", label: "Status", options: orderStatuses },
      { key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] },
      { key: "channel", label: "Channel", options: ["Website", "Website Guest", "WhatsApp", "Manual (Admin)"] },
      { key: "dateOn", label: "Date field", options: [{ value: "created", label: "Order date" }, { value: "delivered", label: "Delivery date" }, { value: "rto", label: "RTO date" }] },
    ],
    dateField: "createdAt",
    dateRange: "Date",
    defaultSort: "createdAt:desc",
    rowHref: "/admin/orders/{id}",
    exportable: true,
    headerActions: [{ label: "Create order", href: "/admin/orders/new", action: "add", primary: true }],
    columns: [
      { key: "id", label: "Order", type: "mono" },
      { key: "customer", label: "Customer", sub: "city" },
      { key: "mobile", label: "Mobile", type: "mono", hidden: true },
      { key: "email", label: "Email", hidden: true },
      { key: "channel", label: "Channel" },
      { key: "paymentMode", label: "Payment", sub: "paymentId" },
      { key: "platformInvoice", label: "Invoice" },
      { key: "items", label: "Lines", type: "number" },
      { key: "vendors", label: "Vendors", type: "number", hidden: true },
      { key: "total", label: "Total", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Placed", type: "datetime", sortable: true },
      { key: "image", label: "Product", type: "image" },
      { key: "productName", label: "Product name", width: 220, sortable: true },
      { key: "invoiceNumber", label: "Seller invoice", type: "mono", sortable: true },
      { key: "salesAgent", label: "Sales agent", width: 180, sortable: true },
      { key: "trackingId", label: "AWB", type: "mono", href: "{trackingUrl}", sortable: true },
      { key: "deliveryDate", label: "Delivered", type: "datetime", sortable: true },
      { key: "rtoDate", label: "RTO date", type: "datetime", sortable: true },
      { key: "prepaidDiscount", label: "Prepaid discount", type: "currency", sortable: true },
      { key: "advanceAmount", label: "Advance", type: "currency", sortable: true },
      { key: "splitSummary", label: "Line status", type: "lineStatus", width: 140, wrap: true, options: manualStatuses },
      { key: "weightIssue", label: "Warning", type: "status" },
      { key: "remarks", label: "Remarks", type: "remarks", width: 240 },
      { key: "verification", label: "Verification", type: "status" },
      { key: "state", label: "State" },
      { key: "pincode", label: "Pincode", type: "mono" },
      { key: "district", label: "District", hidden: true },
      { key: "landHolding", label: "Land holding", hidden: true },
      { key: "season", label: "Season", hidden: true },
      { key: "crop", label: "Crop", hidden: true },
      { key: "soil", label: "Soil", hidden: true },
      { key: "water", label: "Water", hidden: true },
      { key: "callMain", label: "Call status", hidden: true },
      { key: "callAlt", label: "Alt. call", hidden: true },
      { key: "whatsappSent", label: "WhatsApp sent", hidden: true },
      { key: "smsSent", label: "SMS sent", hidden: true },
      { key: "processNote", label: "Process note", width: 220, wrap: true, hidden: true },
    ],
    rowActions: [
      { id: "status", label: "Set status", permission: "edit", assign: { label: "Status", options: manualStatuses, run: true }, confirm: { title: "Update line status?", description: "Sets this status on every product that shares the seller invoice shown on the row." }, when: { field: "invoiceNumber", notIn: ["", null] } },
      { id: "remark", label: "Add remark", permission: "edit", effect: { append: true }, confirm: { title: "Add a remark?", description: "Saved on the order with your name and the time.", requireReason: true } },
      { id: "responsible", label: "Set responsible", permission: "edit", assign: { label: "Responsible party", options: responsibleParties, run: true }, confirm: { title: "Who is responsible?", description: "Used for cancellation, RTO and rejection scoring." } },
      { id: "salesAgent", label: "Set sales agent", permission: "edit", adminOnly: true, assign: { label: "Sales agent", optionsFrom: "lookup:sales-agents", run: true }, confirm: { title: "Credit this order to a sales agent?", description: "Only a super admin can change the sales agent." } },
    ],
  },
  products: {
    title: "All Products",
    description: "Every product listing with pricing, stock and listing-economics verdict. Prices are derived from NRV on the server.",
    permission: "products",
    collection: "products",
    api: "GET /api/admin/products",
    search: "Search name, SKU, brand or vendor",
    searchFields: ["name", "sku", "brand", "vendor", "id", "uniqueId"],
    filterFields: ["parentCategory", "stockStatus", "verdict", "vendorId"],
    filters: [
      { key: "parentCategory", label: "Category", options: categories },
      { key: "stockStatus", label: "Stock", options: ["In Stock", "Low Stock", "Out of Stock"] },
      { key: "verdict", label: "Economics", options: [{ value: "ok", label: "Healthy" }, { value: "below_target", label: "Below target CM" }, { value: "below_floor", label: "Below floor CM" }, { value: "loss", label: "Loss-making" }] },
    ],
    tabs: { field: "status", values: ["Active", "Pending", "Draft / Rejected"] },
    defaultSort: "updatedAt:desc",
    rowHref: "/admin/products/{id}",
    exportable: true,
    headerActions: [
      { label: "Bulk import", href: "/admin/products/import", permission: "products.import", action: "add" },
      { label: "Add product", href: "/admin/products/new", action: "add", primary: true },
    ],
    columns: [
      { key: "image", label: "Image", type: "image" },
      { key: "name", label: "Product", width: 300, sub: "sku", href: "/admin/products/{id}" },
      { key: "vendor", label: "Vendor", width: 180 },
      { key: "category", label: "Category", sub: "parentCategory" },
      { key: "mrp", label: "MRP", type: "currency", sortable: true },
      { key: "display", label: "Display price", type: "currency", sortable: true },
      { key: "nrv", label: "NRV", type: "currency", hidden: true },
      { key: "takeRate", label: "Take rate", type: "percent", hidden: true },
      { key: "gst", label: "GST %", type: "number" },
      { key: "hsn", label: "HSN" },
      { key: "commission", label: "Commission", type: "number", hidden: true },
      { key: "stock", label: "Stock", type: "number", sortable: true },
      { key: "verdict", label: "Economics", type: "status", labels: verdictLabels },
      { key: "status", label: "Status", type: "status" },
      { key: "updatedAt", label: "Updated", type: "date", sortable: true, hidden: true },
    ],
    rowActions: [
      { id: "deactivate", label: "Deactivate listing", permission: "edit", tone: "danger", effect: { set: { statusCode: 2, status: "Pending" } }, when: { field: "statusCode", in: [1] }, confirm: { title: "Deactivate this listing?", description: "It is hidden from the storefront and goes back to the approval queue.", requireReason: true } },
    ],
  },
  inventory: {
    title: "Inventory",
    description: "Live and rejected listings (status 1, 3) by stock level: out of stock = 0, low = 1–9, in stock = 10+. Open a product to adjust stock with a reason.",
    permission: "products",
    collection: "products",
    baseFilter: { statusCode: [1, 3] },
    decorate: (p) => ({ ...p, reorder: p.stock > 0 && p.stock < 50 ? "below50" : "ok" }),
    api: "vendor_product.product_stock → GET /api/admin/inventory",
    search: "Search name, SKU or vendor",
    searchFields: ["name", "sku", "vendor", "brand", "id"],
    filterFields: ["parentCategory", "vendor", "reorder"],
    filters: [
      { key: "parentCategory", label: "Category", options: categories },
      { key: "reorder", label: "Reorder alert", options: [{ value: "below50", label: "Below 50 units" }, { value: "ok", label: "50 units or more / out" }] },
    ],
    tabs: { field: "stockStatus", values: ["Out of Stock", "Low Stock", "In Stock"] },
    defaultSort: "stock:asc",
    rowHref: "/admin/products/{id}",
    exportable: true,
    headerActions: [{ label: "Stock history", href: "/admin/inventory/history" }],
    columns: [
      { key: "name", label: "Product", width: 300, sub: "sku" },
      { key: "vendor", label: "Vendor", width: 180 },
      { key: "category", label: "Category", sub: "parentCategory" },
      { key: "stock", label: "Stock", type: "number", sortable: true, emphasis: true },
      { key: "stockStatus", label: "Level", type: "status" },
      { key: "display", label: "Display price", type: "currency", sortable: true },
      { key: "status", label: "Listing", type: "status" },
      { key: "updatedAt", label: "Updated", type: "date", sortable: true },
    ],
  },
  "inventory.history": {
    title: "Stock History",
    description: "Every stock change with before/after, source and reason. Manual adjustments always carry a reason.",
    permission: "products",
    collection: "stockMovements",
    api: "GET /api/admin/inventory/movements",
    search: "Search product, SKU, vendor or order",
    searchFields: ["product", "sku", "vendor", "reference", "actor"],
    filterFields: ["type"],
    filters: [{ key: "type", label: "Source", options: ["Order placed", "Seller restock", "Return received", "Manual adjustment"] }],
    dateField: "at",
    dateRange: true,
    defaultSort: "at:desc",
    exportable: true,
    headerActions: [{ label: "Inventory", href: "/admin/inventory" }],
    columns: [
      { key: "at", label: "When", type: "datetime", sortable: true },
      { key: "product", label: "Product", width: 260, sub: "sku", href: "/admin/products/{productId}" },
      { key: "vendor", label: "Vendor", width: 160 },
      { key: "type", label: "Source" },
      { key: "before", label: "Before", type: "number" },
      { key: "change", label: "Change", type: "number", emphasis: true },
      { key: "after", label: "After", type: "number" },
      { key: "reference", label: "Order", type: "mono", href: "/admin/orders/{reference}" },
      { key: "reason", label: "Reason", wrap: true },
      { key: "actor", label: "By" },
    ],
  },
  "products.pending": {
    title: "Pending Products",
    description: "New and edited listings waiting for catalog approval. Approving makes the product live (status 1).",
    permission: "products.approval",
    collection: "products",
    baseFilter: { statusCode: [0, 2] },
    api: "GET /api/admin/products?status=pending · POST /api/admin/products/{id}/approve|reject",
    search: "Search name, SKU or vendor",
    searchFields: ["name", "sku", "vendor", "brand"],
    filterFields: ["parentCategory", "verdict"],
    filters: [
      { key: "parentCategory", label: "Category", options: categories },
      { key: "verdict", label: "Economics", options: [{ value: "ok", label: "Healthy" }, { value: "below_target", label: "Below target CM" }, { value: "below_floor", label: "Below floor CM" }, { value: "loss", label: "Loss-making" }] },
    ],
    defaultSort: "createdAt:desc",
    rowHref: "/admin/products/{id}",
    columns: [
      { key: "image", label: "Image", type: "image" },
      { key: "name", label: "Name", width: 260, href: "/admin/products/{id}" },
      { key: "id", label: "Product ID", type: "mono" },
      { key: "sku", label: "SKU", type: "mono" },
      { key: "brand", label: "Brand" },
      { key: "category", label: "Category" },
      { key: "description", label: "Description", wrap: true, width: 220 },
      { key: "hsn", label: "HSN" },
      { key: "mrp", label: "MRP", type: "currency" },
      { key: "display", label: "Sale price", type: "currency" },
      { key: "stock", label: "Stock", type: "number" },
      { key: "vendor", label: "Vendor", width: 160 },
      { key: "weight", label: "Weight" },
      { key: "dimensions", label: "Dimensions" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "approve", label: "Approve", permission: "edit", effect: { set: { statusCode: 1, status: "Active" } }, confirm: { title: "Approve product?", description: "The product goes live on the storefront.", confirmLabel: "Approve" } },
      { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { statusCode: 3, status: "Draft / Rejected" } }, confirm: { title: "Reject product?", description: "The vendor is notified with your reason and can edit and resubmit.", requireReason: true } },
    ],
    bulkActions: [{ id: "approve", label: "Approve selected", permission: "edit", effect: { set: { statusCode: 1, status: "Active" } }, confirm: { title: "Approve {count} products?", description: "All selected products go live on the storefront.", confirmLabel: "Approve" } }],
  },
  vendors: {
    title: "All Vendors",
    description: "Sellers on the marketplace with KYC status, performance score and GMV.",
    permission: "vendors",
    collection: "vendors",
    api: "GET /api/admin/vendors",
    search: "Search firm, owner, GSTIN or ID",
    searchFields: ["name", "owner", "gstin", "id", "city"],
    filterFields: ["kyc", "state"],
    filters: [{ key: "kyc", label: "KYC", options: ["Verified", "Submitted", "Under Review", "Documents Missing", "Rejected"] }],
    tabs: { field: "status", values: ["Active", "Pending", "Suspended", "Rejected"] },
    defaultSort: "gmv:desc",
    rowHref: "/admin/vendors/{id}",
    exportable: true,
    columns: [
      { key: "name", label: "Vendor", width: 240, sub: "id" },
      { key: "owner", label: "Owner" },
      { key: "city", label: "City", sub: "state" },
      { key: "products", label: "Products", type: "number", sortable: true },
      { key: "orders", label: "Order lines", type: "number", sortable: true },
      { key: "gmv", label: "Delivered GMV", type: "currency", sortable: true },
      { key: "score", label: "Score", type: "number", sortable: true },
      { key: "kyc", label: "KYC", type: "status" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "suspend", label: "Suspend vendor", permission: "edit", tone: "danger", effect: { set: { status: "Suspended" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Suspend vendor?", description: "Their listings are hidden and payouts paused until reactivated.", requireReason: true } },
      { id: "reactivate", label: "Reactivate", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", in: ["Suspended"] }, confirm: { title: "Reactivate vendor?", requireReason: true } },
      { id: "verifyBank", label: "Verify bank", permission: "edit", when: { field: "kyc", in: ["Partial", "Pending"] }, confirm: { title: "Mark bank details approved?" } },
      { id: "verifyGst", label: "Verify GST", permission: "edit", when: { field: "kyc", in: ["Partial", "Pending"] }, confirm: { title: "Mark GST certificate approved?" } },
      { id: "verifyPan", label: "Verify PAN", permission: "edit", when: { field: "kyc", in: ["Partial", "Pending"] }, confirm: { title: "Mark PAN card approved?" } },
    ],
  },
  "vendors.scores": {
    title: "Top 10 Dashboard",
    description: "Vendor score = (fulfilment × 25 + dispatch × 20 + revenue × 20 + tenure × 15) / 80 − RTO/cancel penalty × 20%. Recomputed on the server.",
    permission: "vendors.scores",
    collection: "vendors",
    baseFilter: { status: ["Active"] },
    api: "GET /api/admin/vendors/scores",
    search: "Search vendor",
    searchFields: ["name", "id"],
    defaultSort: "score:desc",
    rowHref: "/admin/vendors/{id}",
    exportable: true,
    columns: [
      { key: "name", label: "Vendor", width: 240, sub: "id" },
      { key: "score", label: "Score", type: "number", sortable: true },
      { key: "orders", label: "Order lines", type: "number", sortable: true },
      { key: "gmv", label: "Delivered GMV", type: "currency", sortable: true },
      { key: "dispatchSlaHours", label: "Dispatch SLA (h)", type: "number" },
      { key: "city", label: "City" },
    ],
  },
  customers: {
    title: "Manage All User",
    description: "App users with login method, order count, land holding and account status.",
    permission: "customers",
    collection: "customers",
    api: "GET /api/admin/customers",
    search: "Search name, mobile, email or ID",
    searchFields: ["name", "mobile", "email", "id", "userId", "city"],
    filterFields: ["loginMethod", "state"],
    filters: [{ key: "loginMethod", label: "Login", options: [{ value: "general", label: "General" }, { value: "guest", label: "Guest" }, { value: "google", label: "Google" }, { value: "facebook", label: "Facebook" }, { value: "Model Login", label: "Model Login" }] }],
    tabs: { field: "status", values: ["Active", "Inactive", "Blocked"] },
    defaultSort: "createdAt:desc",
    rowHref: "/admin/customers/{id}",
    exportable: true,
    columns: [
      { key: "name", label: "Name", sub: "userId" },
      { key: "mobile", label: "Phone", type: "mobile" },
      { key: "loginMethod", label: "Login Method" },
      { key: "createdBy", label: "Created By" },
      { key: "orders", label: "No of Orders", type: "number", sortable: true },
      { key: "email", label: "Email" },
      { key: "landValue", label: "Land Value" },
      { key: "landUnit", label: "Land Unit" },
      { key: "city", label: "City", sub: "state" },
      { key: "createdAt", label: "Created Date", type: "datetime", sortable: true },
      { key: "lifetimeValue", label: "Lifetime value", type: "currency", sortable: true },
      { key: "walletBalance", label: "Wallet", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "block", label: "Block customer", permission: "edit", tone: "danger", effect: { set: { status: "Blocked" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Block customer?", description: "They will not be able to log in or place orders.", requireReason: true } },
      { id: "deactivate", label: "Mark inactive", permission: "edit", when: { field: "status", in: ["Active"] }, confirm: { title: "Mark this customer inactive?" } },
      { id: "unblock", label: "Unblock", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", in: ["Blocked", "Inactive"] }, confirm: { title: "Activate customer?", requireReason: true } },
    ],
  },
  shipping: {
    title: "Shipping Queue",
    description: "Vendor shipments by order line. Ready-to-ship lines need a courier booking (NimbusPost primary, Shiprocket/Delhivery fallback).",
    permission: "shipping",
    collection: "shipments",
    api: "GET /api/admin/shipments",
    search: "Search order, AWB, vendor or pincode",
    searchFields: ["orderId", "awb", "vendor", "customer", "pincode"],
    filterFields: ["courier", "paymentMode", "zone"],
    filters: [
      { key: "courier", label: "Courier", options: couriers },
      { key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] },
    ],
    tabs: { field: "status", values: ["Ready to Ship", "Pending Pickup", "Shipped", "In Transit", "Out for Delivery", "Delivered", "Undelivered", "RTO"] },
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "vendor", label: "Vendor", width: 200 },
      { key: "customer", label: "Customer", sub: "pincode" },
      { key: "zone", label: "Zone" },
      { key: "weightKg", label: "Weight (kg)", type: "number" },
      { key: "collectAmount", label: "COD collect", type: "currency" },
      { key: "courier", label: "Courier", sub: "awb" },
      { key: "status", label: "Status", type: "status" },
      { key: "slaDue", label: "Dispatch SLA", type: "datetime", sortable: true },
    ],
  },
  returns: {
    title: "Returns",
    description: "Customer return requests per order line. Refund = item price + GST (+ shipping if refunded) − platform fee if deducted, computed on the server.",
    permission: "returns",
    collection: "returns",
    api: "GET /api/admin/returns",
    search: "Search return, order, product or customer",
    searchFields: ["returnId", "orderId", "product", "customer", "vendor", "mobile", "trackingId"],
    filterFields: ["reason", "paymentMode"],
    filters: [
      { key: "reason", label: "Reason", options: ["Wrong Product", "Damaged in Transit", "Customer Didn't Like", "Exchange Requested", "Quality Issue", "Other"] },
      { key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] },
    ],
    tabs: { field: "status", values: ["Pending", "Awaiting Pickup", "In Transit", "Received", "Refunded", "Replacement Shipped", "Completed", "Rejected"] },
    dateField: "createdAt",
    dateRange: "Requested",
    defaultSort: "createdAt:desc",
    rowHref: "/admin/returns/{id}",
    exportable: true,
    columns: [
      { key: "returnId", label: "Return", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "product", label: "Product", width: 240 },
      { key: "customer", label: "Customer" },
      { key: "mobile", label: "Mobile", type: "mono" },
      // In the CSV export like the PHP grid's Payment column; shown from "Columns".
      { key: "paymentMode", label: "Payment", hidden: true },
      { key: "reason", label: "Reason" },
      { key: "refundAmount", label: "Refund", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
      { key: "trackingId", label: "AWB / Tracking", type: "mono" },
      { key: "createdAt", label: "Requested", type: "datetime", sortable: true },
    ],
    // The manage_returns.php grid "Actions" menu.
    rowActions: [
      { id: "process", label: "Process Return/Refund", href: "/admin/returns/{id}", permission: "view" },
      { id: "shipment", label: "Create Return Shipment", href: "/admin/returns/{id}?shipment=1", permission: "edit", when: { field: "status", in: ["Pending", "Awaiting Pickup"] } },
    ],
    bulkActions: [
      { id: "approve", label: "Bulk approve", permission: "edit", confirm: { title: "Approve the selected returns?", description: "Pending returns among the {count} selected move to Awaiting Pickup. Others are skipped.", confirmLabel: "Approve" } },
      { id: "picked", label: "Bulk mark as picked", permission: "edit", confirm: { title: "Mark the selected returns as picked?", description: "Returns awaiting pickup among the {count} selected move to In Transit with today's pickup date. Others are skipped.", confirmLabel: "Mark as picked" } },
    ],
  },
  refunds: {
    title: "Refunds",
    description: "Razorpay refunds for prepaid orders and manual bank transfers for COD returns.",
    permission: "refunds",
    collection: "refunds",
    api: "GET /api/admin/refunds",
    search: "Search refund, return, order or customer",
    searchFields: ["id", "returnId", "orderId", "customer"],
    filterFields: ["method"],
    filters: [{ key: "method", label: "Method", options: ["Razorpay refund", "Bank transfer (manual)"] }],
    tabs: { field: "status", values: ["Initiated", "Pending Manual Transfer", "Processed"] },
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "id", label: "Refund", type: "mono" },
      { key: "returnId", label: "Return", type: "mono", href: "/admin/returns/{returnId}" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "customer", label: "Customer" },
      { key: "amount", label: "Amount", type: "currency", sortable: true },
      { key: "method", label: "Method" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "processed", label: "Mark transfer done", permission: "edit", effect: { set: { status: "Processed" } }, when: { field: "status", in: ["Pending Manual Transfer"] }, confirm: { title: "Confirm bank transfer completed?", description: "Enter the bank UTR / reference in the reason. This is recorded in the audit log.", requireReason: true, confirmLabel: "Mark processed" } },
    ],
  },
  rto: {
    title: "RTO",
    description: "Return-to-origin shipments. Forward + reverse shipping is booked to the RTO ledger when the parcel reaches the vendor.",
    permission: "rto",
    collection: "rto",
    api: "GET /api/admin/rto",
    search: "Search order, AWB, vendor",
    searchFields: ["orderId", "awb", "vendor", "customer", "product"],
    filterFields: ["courier", "reason", "paymentMode"],
    filters: [
      { key: "courier", label: "Courier", options: couriers },
      { key: "reason", label: "Reason", options: ["Customer refused", "Address not found", "Customer not reachable", "COD amount not ready", "Fake order"] },
    ],
    tabs: { field: "status", values: ["RTO In Transit", "RTO Delivered"] },
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "product", label: "Product", width: 220 },
      { key: "vendor", label: "Vendor" },
      { key: "courier", label: "Courier", sub: "awb" },
      { key: "reason", label: "Reason" },
      { key: "value", label: "Value", type: "currency" },
      { key: "forwardShipping", label: "Fwd ship", type: "currency" },
      { key: "reverseShipping", label: "Rev ship", type: "currency" },
      { key: "ledgerRecorded", label: "Ledger", type: "boolean", trueLabel: "Recorded", falseLabel: "Pending" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "ledger", label: "Record in RTO ledger", permission: "edit", effect: { set: { ledgerRecorded: true } }, when: { field: "ledgerRecorded", in: [false] }, confirm: { title: "Record RTO cost?", description: "Forward and reverse shipping are booked as an RTO expense (idempotent per AWB on the server)." } },
    ],
  },
  payouts: {
    title: "Payout Cycles",
    description: "Vendor payouts grouped by cycle (1st–15th, 16th–month end). Paid only after a transaction ID and proof are recorded.",
    permission: "payouts",
    collection: "payouts",
    api: "GET /api/payout/* → /api/admin/payouts",
    search: "Search payout, vendor or UTR",
    searchFields: ["id", "vendor", "vendorId", "transactionId"],
    filterFields: ["cycle"],
    tabs: { field: "status", values: ["Pending", "On Hold", "Paid"] },
    defaultSort: "cycleIndex:desc",
    rowHref: "/admin/payouts/{id}",
    exportable: true,
    columns: [
      { key: "id", label: "Payout", type: "mono" },
      { key: "vendor", label: "Vendor", width: 220, sub: "vendorId" },
      { key: "cycle", label: "Cycle" },
      { key: "items", label: "Lines", type: "number" },
      { key: "gross", label: "Gross", type: "currency" },
      { key: "tcs", label: "TCS", type: "currency" },
      { key: "bsa", label: "Payable (BSA)", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
      { key: "transactionId", label: "UTR", type: "mono" },
    ],
  },
  support: {
    title: "Support Tickets",
    description: "Customer and vendor helpdesk. SLA depends on priority and category; internal notes are never shown to the requester.",
    permission: "support",
    collection: "tickets",
    api: "GET /api/admin/support/tickets",
    search: "Search ticket, subject, requester or order",
    searchFields: ["id", "subject", "user", "orderId"],
    filterFields: ["userType", "priority", "department", "category"],
    filters: [
      { key: "userType", label: "Requester", options: [{ value: "customer", label: "Customer" }, { value: "vendor", label: "Vendor" }] },
      { key: "priority", label: "Priority", options: ["Urgent", "Normal"] },
      { key: "department", label: "Department", options: ["Finance", "Logistics", "Tech", "Vendor Support", "Unassigned"] },
    ],
    tabs: { field: "status", values: ["Open", "In-Progress", "Awaiting Response", "Resolved", "Closed", "Rejected"] },
    defaultSort: "createdAt:desc",
    rowHref: "/admin/support/{id}",
    // Same columns as the PHP grid (support/admin_dashboard.php); SLA due turns red once overdue.
    columns: [
      { key: "id", label: "ID", type: "mono", sortable: true },
      { key: "userType", label: "Type", type: "status", labels: { Seller: "Vendor" } },
      { key: "subject", label: "Subject", width: 260, emphasis: true },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority", type: "status" },
      { key: "slaDeadline", label: "SLA Due", type: "datetime", sortable: true, dangerKey: "slaOverdue" },
      { key: "status", label: "Status", type: "status" },
      { key: "user", label: "Requester", hidden: true },
      { key: "department", label: "Department", hidden: true },
      { key: "createdAt", label: "Created", type: "datetime", sortable: true, hidden: true },
    ],
  },
  "crm.followUps": {
    title: "Follow-ups",
    description: "Leads with a scheduled follow-up, most overdue first. Executives see only their own.",
    permission: "crm.leads",
    collection: "leads",
    ownerField: "assignedTo",
    baseFilter: (row) => Boolean(row.nextFollowUp),
    api: "GET /api/crm_leads/followups",
    search: "Search name, mobile or crop",
    searchFields: ["name", "mobile", "crop"],
    filterFields: ["assignedTo", "priority", "due"],
    filters: [
      { key: "due", label: "Due", options: [{ value: "overdue", label: "Overdue" }, { value: "upcoming", label: "Upcoming" }] },
      { key: "priority", label: "Priority", options: ["Hot", "Warm", "Cold"] },
    ],
    decorate: (row) => ({ ...row, due: new Date(row.nextFollowUp).getTime() <= NOW ? "overdue" : "upcoming" }),
    defaultSort: "nextFollowUp:asc",
    rowHref: "/admin/crm/leads/{id}",
    columns: [
      { key: "name", label: "Lead", sub: "id" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "crop", label: "Crop" },
      { key: "priority", label: "Priority", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "assignedTo", label: "Executive" },
      { key: "due", label: "Due", type: "status", labels: { overdue: "Overdue", upcoming: "Upcoming" } },
      { key: "nextFollowUp", label: "Follow-up at", type: "datetime", sortable: true },
    ],
  },
};
