const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Delete permanently?", description: "This cannot be undone." } };
const execs = ["Rupesh Kumar", "Anjali Verma", "Imran Khan", "Sneha Patidar", "Vivek Rathore", "Kajal Meena"];
const months = [{ value: "2026-10", label: "Oct 2026" }];

export const crmResources = {
  "crm.leads": {
    title: "CRM Lead Sheet",
    description: "One lead per mobile. Leads are auto-assigned by telecom circle to the executive with the fewest live leads. Executives see only their own leads.",
    permission: "crm.leads",
    collection: "leads",
    ownerField: "assignedTo",
    api: "GET /api/crm_leads/* → /api/admin/crm/leads",
    search: "Search name, mobile, crop or city",
    searchFields: ["name", "mobile", "crop", "city", "id"],
    filterFields: ["status", "priority", "source", "assignedTo"],
    filters: [
      { key: "priority", label: "Priority", options: ["Hot", "Warm", "Cold"] },
      { key: "source", label: "Source", options: ["WhatsApp", "Website Engagement", "Bulk Inquiry", "CSV Import", "AI Call (VAPI)", "Missed Call"] },
      { key: "assignedTo", label: "Executive", options: execs },
    ],
    tabs: { field: "status", values: ["New", "Called", "Interested", "Follow Up", "Not Interested", "Converted"] },
    dateField: "createdAt",
    dateRange: "Created",
    defaultSort: "createdAt:desc",
    rowHref: "/admin/crm/leads/{id}",
    exportable: true,
    columns: [
      { key: "name", label: "Lead", sub: "id" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "crop", label: "Crop", sub: "acreage" },
      { key: "city", label: "Location", sub: "state" },
      { key: "source", label: "Source" },
      { key: "priority", label: "Priority", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "assignedTo", label: "Executive" },
      { key: "attempts", label: "Attempts", type: "number", sortable: true },
      { key: "nextFollowUp", label: "Next follow-up", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "hot", label: "Mark Hot", permission: "edit", effect: { set: { priority: "Hot" } }, when: { field: "priority", notIn: ["Hot"] } },
      { id: "notInterested", label: "Mark Not Interested", permission: "edit", tone: "danger", effect: { set: { status: "Not Interested", nextFollowUp: null } }, when: { field: "status", notIn: ["Converted", "Not Interested"] }, confirm: { title: "Close lead as Not Interested?", description: "Follow-ups for this lead will stop." } },
    ],
    bulkActions: [{ id: "reassign", label: "Reassign…", permission: "edit", assign: { field: "assignedTo", label: "Assign to executive", options: execs }, confirm: { title: "Reassign selected leads?", description: "Leads move to the chosen executive's sheet." } }],
    form: {
      title: "Add lead",
      fields: [
        { name: "name", label: "Farmer name", type: "text", required: true },
        { name: "mobile", label: "Mobile", type: "text", required: true, pattern: "^[6-9][0-9]{9}$", patternMessage: "Enter a 10-digit Indian mobile number." },
        { name: "crop", label: "Crop", type: "text", required: true },
        { name: "acreage", label: "Acreage", type: "number", min: 0, max: 1000 },
        { name: "city", label: "District / city", type: "text" },
        { name: "source", label: "Source", type: "select", options: ["Missed Call", "WhatsApp", "Website Engagement", "Bulk Inquiry", "CSV Import"], required: true },
        { name: "priority", label: "Priority", type: "select", options: ["Hot", "Warm", "Cold"], required: true },
      ],
      defaults: { status: "New", attempts: 0, orderValue: 0, assignedTo: "Auto-assign by circle" },
      unique: "mobile",
    },
  },
  "crm.legacy": {
    title: "All Leads (Legacy)",
    description: "Leads from the older manager/agent lead pages. Kept read-only for history; new work happens in the CRM Lead Sheet.",
    permission: "crm.legacy",
    collection: "legacyLeads",
    api: "GET /api/admin/crm/legacy-leads",
    search: "Search name or mobile",
    searchFields: ["name", "mobile"],
    filterFields: ["agent", "status", "circle"],
    filters: [
      { key: "agent", label: "Agent", options: execs },
      { key: "status", label: "Status", options: ["Call Scheduled", "Call Done", "In Progress", "Requirement Shared", "Order Generated", "Dead", "Done"] },
    ],
    defaultSort: "createdAt:desc",
    columns: [
      { key: "name", label: "Lead", sub: "id" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "circle", label: "Circle" },
      { key: "agent", label: "Agent" },
      { key: "source", label: "Source" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
  },
  "crm.whatsapp": {
    title: "WhatsApp Leads",
    description: "WhatsApp bot sessions. Synced sessions become CRM leads.",
    permission: "crm.whatsapp",
    collection: "whatsappLeads",
    api: "GET /api/admin/crm/whatsapp-sessions",
    search: "Search name or mobile",
    searchFields: ["name", "mobile", "lastMessage"],
    filterFields: ["state", "language"],
    filters: [
      { key: "state", label: "Bot state", options: ["main_menu", "crop_problem", "browse_products", "cart", "checkout", "track_order", "expert"] },
      { key: "language", label: "Language", options: ["Hindi", "English"] },
    ],
    defaultSort: "lastActiveAt:desc",
    columns: [
      { key: "name", label: "Contact", sub: "id" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "language", label: "Language" },
      { key: "state", label: "Bot state" },
      { key: "lastMessage", label: "Last message", width: 260 },
      { key: "syncedToCrm", label: "In CRM", type: "boolean" },
      { key: "lastActiveAt", label: "Last active", type: "datetime", sortable: true },
    ],
    rowActions: [{ id: "sync", label: "Create CRM lead", permission: "edit", effect: { set: { syncedToCrm: true } }, when: { field: "syncedToCrm", in: [false] } }],
    bulkActions: [{ id: "sync", label: "Create CRM leads", permission: "edit", effect: { set: { syncedToCrm: true } } }],
  },
  "crm.aiCalls": {
    title: "AI Calls (VAPI)",
    description: "Leads dispatched to the VAPI AI calling agent through n8n.",
    permission: "crm.aiCalls",
    collection: "aiCalls",
    api: "GET /api/vapi/* → /api/admin/crm/ai-calls",
    searchFields: ["lead", "mobile", "id"],
    tabs: { field: "status", values: ["queued", "calling", "completed", "no-answer", "failed"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Call", type: "mono" },
      { key: "lead", label: "Lead" },
      { key: "mobile", label: "Mobile", type: "mobile" },
      { key: "status", label: "Status", type: "status" },
      { key: "durationSec", label: "Duration (s)", type: "number", sortable: true },
      { key: "outcome", label: "Outcome" },
      { key: "createdAt", label: "Queued", type: "datetime", sortable: true },
    ],
    rowActions: [{ id: "requeue", label: "Re-queue call", permission: "edit", effect: { set: { status: "queued" } }, when: { field: "status", in: ["failed", "no-answer"] } }],
  },
  "crm.callAudit": {
    title: "AI Call Audit",
    description: "Telesales recordings transcribed and scored against the 8-stage, 37-checkpoint script. Scores are computed on the server, not by the model.",
    permission: "crm.callAudit",
    collection: "callAudits",
    api: "GET /api/call_audit/data.php → /api/admin/crm/call-audits",
    search: "Search executive or farmer",
    searchFields: ["executive", "farmer", "id"],
    filterFields: ["executive", "grade", "language"],
    filters: [
      { key: "executive", label: "Executive", options: execs },
      { key: "grade", label: "Grade", options: ["A", "B", "C", "D"] },
      { key: "language", label: "Language", options: ["hi", "hi-en", "mr", "gu", "bho"] },
    ],
    tabs: { field: "status", values: ["Scored", "Processing", "Failed"] },
    defaultSort: "callDate:desc",
    columns: [
      { key: "id", label: "Audit", type: "mono" },
      { key: "executive", label: "Executive" },
      { key: "farmer", label: "Farmer" },
      { key: "callDate", label: "Call date", type: "date", sortable: true },
      { key: "language", label: "Language" },
      { key: "overall", label: "Score", type: "number", sortable: true },
      { key: "compliance", label: "Compliance %", type: "percent", sortable: true },
      { key: "grade", label: "Grade" },
      { key: "outcome", label: "Outcome" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "retry", label: "Retry audit", permission: "edit", effect: { set: { status: "Processing" } }, when: { field: "status", in: ["Failed"] } }],
  },
  "crm.circles": {
    title: "Circle Assignment",
    description: "Mobile prefix → telecom circle → sales executives. Used for automatic lead assignment.",
    permission: "crm.circles",
    collection: "circles",
    api: "GET /api/admin/crm/circles",
    searchFields: ["prefix", "circle"],
    columns: [
      { key: "prefix", label: "Mobile prefix", type: "mono" },
      { key: "circle", label: "Circle", emphasis: true },
      { key: "agents", label: "Executives covering", width: 320 },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: { fields: [{ name: "prefix", label: "Prefix (4 digits)", type: "text", required: true, pattern: "^[6-9][0-9]{3}$", patternMessage: "4 digits starting 6–9." }, { name: "circle", label: "Circle", type: "text", required: true }], defaults: { agents: "Unassigned" } },
  },
  "sales.targets": {
    title: "Targets",
    description: "Monthly targets per executive, manager, or combined team. Daily target = monthly / days + yesterday's shortfall.",
    permission: "sales.targets",
    collection: "salesTargets",
    api: "POST /api/sales_targets/targets_data.php → /api/admin/sales/targets",
    searchFields: ["person"],
    filterFields: ["targetType", "month"],
    filters: [
      { key: "targetType", label: "Type", options: ["sales_executive", "sales_manager", "overall_executive", "overall_manager"] },
      { key: "month", label: "Month", options: months },
    ],
    columns: [
      { key: "person", label: "Sales person", emphasis: true },
      { key: "targetType", label: "Target type" },
      { key: "experience", label: "Experience" },
      { key: "month", label: "Month" },
      { key: "target", label: "Target", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      title: "Assign target",
      fields: [
        { name: "person", label: "Sales person", type: "select", options: [...execs, "Nitin Sharma", "Pallavi Joshi", "All executives", "All managers"], required: true },
        { name: "targetType", label: "Target type", type: "select", options: ["sales_executive", "sales_manager", "overall_executive", "overall_manager"], required: true },
        { name: "month", label: "Month (YYYY-MM)", type: "text", required: true, pattern: "^20[0-9]{2}-(0[1-9]|1[0-2])$", patternMessage: "Use YYYY-MM." },
        { name: "target", label: "Target amount (₹)", type: "number", required: true, min: 1000 },
      ],
      defaults: { status: "Active", experience: "—" },
    },
  },
  "sales.salary": {
    title: "Salary Structure",
    description: "Fixed salary, variable pay (paid only when target met) and incentive (on excess achievement), with effective dates.",
    permission: "sales.salary",
    collection: "salaryStructures",
    api: "POST /api/sales_targets/salary_structure_data.php → /api/admin/sales/salary-structures",
    searchFields: ["person"],
    filterFields: ["role"],
    filters: [{ key: "role", label: "Role", options: ["Sales Executive", "Sales Manager"] }],
    columns: [
      { key: "person", label: "Sales person", emphasis: true, sub: "role" },
      { key: "fixedSalary", label: "Fixed", type: "currency", sortable: true },
      { key: "variableValue", label: "Variable % of target", type: "percent" },
      { key: "incentiveValue", label: "Incentive % of excess", type: "percent" },
      { key: "effectiveFrom", label: "Effective from", type: "date" },
      { key: "status", label: "Status", type: "status" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: {
      fields: [
        { name: "fixedSalary", label: "Fixed monthly salary (₹)", type: "number", required: true, min: 0 },
        { name: "variableValue", label: "Variable pay % of target", type: "number", required: true, min: 0, max: 20 },
        { name: "incentiveValue", label: "Incentive % of excess", type: "number", required: true, min: 0, max: 20 },
        { name: "effectiveFrom", label: "Effective from", type: "date", required: true },
      ],
      requireReason: true,
    },
  },
  "sales.achievements": {
    title: "Achievements",
    description: "Monthly achievement = delivered, non-returned line amounts by orders.salesman_id (calculated on the server).",
    permission: "sales.targets",
    collection: "achievements",
    api: "POST /api/sales_targets/achievements_data.php?action=calculate",
    searchFields: ["person"],
    filterFields: ["role"],
    defaultSort: "percent:desc",
    columns: [
      { key: "person", label: "Sales person", emphasis: true, sub: "role" },
      { key: "month", label: "Month" },
      { key: "target", label: "Target", type: "currency" },
      { key: "achieved", label: "Achieved", type: "currency", sortable: true },
      { key: "percent", label: "Achievement %", type: "percent", sortable: true },
      { key: "prepaidShare", label: "Prepaid share %", type: "percent", sortable: true },
      { key: "orders", label: "Orders", type: "number" },
    ],
  },
  "sales.payouts": {
    title: "Sales Payouts",
    description: "Fixed + variable (if target met) + incentive (if exceeded) + prepaid incentive. Managers get variable only if their team met target.",
    permission: "sales.payouts",
    collection: "salesPayouts",
    api: "POST /api/sales_targets/payouts_data.php",
    searchFields: ["person"],
    tabs: { field: "status", values: ["Pending", "Processed", "Paid", "Cancelled"] },
    exportable: true,
    columns: [
      { key: "person", label: "Sales person", emphasis: true, sub: "role" },
      { key: "month", label: "Month" },
      { key: "fixed", label: "Fixed", type: "currency" },
      { key: "variable", label: "Variable", type: "currency" },
      { key: "incentive", label: "Incentive", type: "currency" },
      { key: "prepaidIncentive", label: "Prepaid incentive", type: "currency" },
      { key: "total", label: "Total", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "process", label: "Mark processed", permission: "edit", effect: { set: { status: "Processed" } }, when: { field: "status", in: ["Pending"] } },
      { id: "paid", label: "Mark paid", permission: "edit", effect: { set: { status: "Paid" } }, when: { field: "status", in: ["Processed"] }, confirm: { title: "Mark salary payout paid?", description: "Confirm the payment has been made.", requireReason: true } },
      { id: "cancel", label: "Cancel", permission: "edit", tone: "danger", effect: { set: { status: "Cancelled" } }, when: { field: "status", in: ["Pending", "Processed"] }, confirm: { title: "Cancel payout?", requireReason: true } },
    ],
  },
  "sales.prepaid": {
    title: "Prepaid Incentive Setup",
    description: "Executives with prepaid share ≥ threshold earn a % of their prepaid amount; managers earn a % of all executives' prepaid amount.",
    permission: "sales.salary",
    collection: "prepaidConfig",
    api: "GET/POST /api/admin/sales/prepaid-incentive-config",
    columns: [
      { key: "role", label: "Role", emphasis: true },
      { key: "thresholdPercent", label: "Prepaid threshold", type: "percent" },
      { key: "incentivePercent", label: "Incentive %", type: "percent" },
      { key: "basis", label: "Basis" },
      { key: "status", label: "Status", type: "status" },
    ],
    noAdd: true,
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }],
    form: {
      fields: [
        { name: "thresholdPercent", label: "Prepaid share threshold %", type: "number", min: 0, max: 100, required: true },
        { name: "incentivePercent", label: "Incentive %", type: "number", min: 0, max: 10, required: true },
      ],
      requireReason: true,
    },
  },
};
