const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Delete permanently?", description: "This cannot be undone." } };

export const financeResources = {
  "vendors.verification": {
    title: "Vendor Verification",
    description: "New sellers awaiting KYC, GST and bank verification before they can list products.",
    permission: "vendors.verification",
    collection: "vendors",
    baseFilter: { status: ["Pending", "Rejected"] },
    api: "GET /api/admin/vendors?status=pending",
    search: "Search firm, owner, GSTIN",
    searchFields: ["name", "owner", "gstin", "id"],
    filterFields: ["kyc"],
    filters: [{ key: "kyc", label: "KYC", options: ["Submitted", "Under Review", "Documents Missing", "Rejected"] }],
    rowHref: "/admin/vendors/{id}",
    defaultSort: "onboardedAt:desc",
    columns: [
      { key: "name", label: "Vendor", sub: "id" },
      { key: "owner", label: "Owner" },
      { key: "city", label: "City", sub: "state" },
      { key: "gstin", label: "GSTIN", type: "mono" },
      { key: "kyc", label: "KYC", type: "status" },
      { key: "status", label: "Status", type: "status" },
      { key: "onboardedAt", label: "Applied", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "verify", label: "Verify & activate", permission: "edit", effect: { set: { status: "Active", kyc: "Verified" } }, when: { field: "status", in: ["Pending"] }, confirm: { title: "Activate vendor?", description: "KYC will be marked verified and the vendor can list products.", confirmLabel: "Activate" } },
      { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { status: "Rejected", kyc: "Rejected" } }, when: { field: "status", in: ["Pending"] }, confirm: { title: "Reject application?", description: "The vendor will be notified with your reason.", requireReason: true } },
    ],
  },
  "vendors.reports": {
    title: "Vendor Reports",
    description: "Vendor-wise orders, delivered GMV and RTO for performance reviews.",
    permission: "vendors.reports",
    collection: "vendorReportRows",
    api: "GET /api/admin/reports/vendors",
    search: "Search vendor",
    searchFields: ["vendor"],
    defaultSort: "gmv:desc",
    exportable: true,
    columns: [
      { key: "vendor", label: "Vendor", emphasis: true, sub: "id" },
      { key: "orders", label: "Order lines", type: "number", sortable: true },
      { key: "delivered", label: "Delivered", type: "number", sortable: true },
      { key: "rto", label: "RTO", type: "number", sortable: true },
      { key: "rtoPct", label: "RTO %", type: "percent", sortable: true },
      { key: "gmv", label: "Delivered GMV", type: "currency", sortable: true },
      { key: "bsa", label: "Seller payable (BSA)", type: "currency", sortable: true },
    ],
  },
  "finance.ledger": {
    title: "Ledger Management",
    description: "Customer, vendor and wallet ledgers built from hold-ledger notes, settlements and wallet movements.",
    permission: "finance.ledger",
    collection: "ledger",
    api: "GET /api/admin/finance/ledger?type=",
    search: "Search party or reference",
    searchFields: ["party", "reference", "narration"],
    filterFields: ["ledger"],
    tabs: { field: "ledger", values: ["Customer", "Vendor", "Wallet"] },
    dateField: "createdAt",
    dateRange: true,
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "createdAt", label: "Date", type: "date", sortable: true },
      { key: "ledger", label: "Ledger", type: "status" },
      { key: "party", label: "Party", emphasis: true },
      { key: "reference", label: "Reference", type: "mono" },
      { key: "narration", label: "Narration", width: 240 },
      { key: "debit", label: "Debit", type: "currency", sortable: true },
      { key: "credit", label: "Credit", type: "currency", sortable: true },
    ],
  },
  "finance.holdLedger": {
    title: "Hold Ledger (CN/DN)",
    description: "Credit and debit notes for customers, vendors, internal and logistics parties. Total = taxable + CGST + SGST + IGST. Every action is written to hold_ledger_audit.",
    permission: "finance.holdLedger",
    collection: "holdLedger",
    api: "GET/POST /api/admin/finance/hold-ledger",
    search: "Search note, party or order",
    searchFields: ["id", "partyName", "orderId", "reason"],
    filterFields: ["party", "type", "status"],
    filters: [
      { key: "party", label: "Party", options: ["CUSTOMER", "VENDOR", "BAL_INTERNAL", "LOGISTICS"] },
      { key: "type", label: "Type", options: ["Credit Note", "Debit Note"] },
    ],
    tabs: { field: "status", values: ["PENDING", "UNDER_REVIEW", "APPROVED", "RELEASED", "DISPUTED", "DEFERRED"] },
    dateField: "createdAt",
    dateRange: true,
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "id", label: "Note", type: "mono" },
      { key: "type", label: "Type" },
      { key: "party", label: "Party", sub: "partyName" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "reason", label: "Reason", width: 200 },
      { key: "taxable", label: "Taxable", type: "currency" },
      { key: "total", label: "Total", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "review", label: "Move to review", permission: "edit", effect: { set: { status: "UNDER_REVIEW" } }, when: { field: "status", in: ["PENDING", "DEFERRED"] } },
      { id: "approve", label: "Approve", permission: "edit", effect: { set: { status: "APPROVED" } }, when: { field: "status", in: ["UNDER_REVIEW"] }, confirm: { title: "Approve note?", description: "Approved notes can be released to the party.", requireReason: true } },
      { id: "release", label: "Release", permission: "edit", effect: { set: { status: "RELEASED" } }, when: { field: "status", in: ["APPROVED"] }, confirm: { title: "Release note?", description: "Customer credit notes released as BAL Wallet Credit credit the wallet once (idempotent on the server).", requireReason: true } },
      { id: "dispute", label: "Mark disputed", permission: "edit", tone: "danger", effect: { set: { status: "DISPUTED" } }, when: { field: "status", notIn: ["RELEASED", "DISPUTED"] }, confirm: { title: "Mark as disputed?", description: "The note is frozen until the dispute is resolved.", requireReason: true } },
      { id: "defer", label: "Defer", permission: "edit", effect: { set: { status: "DEFERRED" } }, when: { field: "status", in: ["PENDING", "UNDER_REVIEW"] }, confirm: { title: "Defer note?", requireReason: true } },
      { id: "reopen", label: "Reopen", permission: "edit", effect: { set: { status: "PENDING" } }, when: { field: "status", in: ["DISPUTED", "RELEASED"] }, confirm: { title: "Reopen note?", requireReason: true } },
    ],
    form: {
      title: "New credit / debit note",
      fields: [
        { name: "type", label: "Type", type: "select", options: ["Credit Note", "Debit Note"], required: true },
        { name: "party", label: "Party", type: "select", options: ["CUSTOMER", "VENDOR", "BAL_INTERNAL", "LOGISTICS"], required: true },
        { name: "partyName", label: "Party name", type: "text", required: true },
        { name: "orderId", label: "Order ID", type: "text" },
        { name: "reason", label: "Reason", type: "text", required: true },
        { name: "taxable", label: "Taxable value (₹)", type: "number", required: true, min: 1, max: 1000000 },
        { name: "supply", label: "Supply", type: "select", options: ["Intra-state (CGST + SGST)", "Inter-state (IGST)"], required: true },
      ],
      defaults: { status: "PENDING" },
      derive: "holdLedger",
      requireReason: true,
    },
  },
  "finance.cod": {
    title: "COD Reconciliation",
    description: "Courier COD remittances: expected vs received, pending by courier.",
    permission: "finance",
    collection: "codRecon",
    api: "GET /api/admin/finance/cod-reconciliation",
    filterFields: ["courier", "status"],
    filters: [{ key: "courier", label: "Courier", options: ["NimbusPost", "Shiprocket", "Delhivery"] }],
    tabs: { field: "status", values: ["Pending", "Partially Reconciled", "Reconciled"] },
    defaultSort: "remittanceDate:desc",
    exportable: true,
    columns: [
      { key: "id", label: "Remittance", type: "mono" },
      { key: "courier", label: "Courier" },
      { key: "remittanceDate", label: "Date", type: "date", sortable: true },
      { key: "shipments", label: "Shipments", type: "number" },
      { key: "expected", label: "Expected", type: "currency", sortable: true },
      { key: "received", label: "Received", type: "currency" },
      { key: "pending", label: "Pending", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "reconcile", label: "Mark reconciled", permission: "edit", effect: { set: { status: "Reconciled" } }, when: { field: "status", notIn: ["Reconciled"] }, confirm: { title: "Mark remittance reconciled?", description: "Confirm the bank credit matches the courier statement.", requireReason: true } }],
  },
  "finance.tax": {
    title: "GST & TCS",
    description: "Monthly output GST, input credit, net liability, TCS collected and TDS deducted.",
    permission: "finance.tax",
    collection: "gstMonthly",
    api: "GET /api/admin/finance/gst-summary",
    exportable: true,
    columns: [
      { key: "month", label: "Month", emphasis: true },
      { key: "taxableSales", label: "Taxable sales", type: "currency" },
      { key: "cgst", label: "CGST", type: "currency" },
      { key: "sgst", label: "SGST", type: "currency" },
      { key: "igst", label: "IGST", type: "currency" },
      { key: "outputGst", label: "Output GST", type: "currency" },
      { key: "inputCredit", label: "Input credit", type: "currency" },
      { key: "netLiability", label: "Net liability", type: "currency" },
      { key: "tcsCollected", label: "TCS", type: "currency" },
      { key: "tdsDeducted", label: "TDS", type: "currency" },
      { key: "status", label: "Return", type: "status" },
    ],
  },
  "finance.fixedExpenses": {
    title: "Fixed Expenses",
    description: "Recurring fixed costs with monthly overrides, pro-rated by days in the P&L and expense-limit dashboard.",
    permission: "finance.expenses",
    collection: "fixedExpenses",
    api: "GET/POST /api/admin/finance/fixed-expenses",
    searchFields: ["name", "category"],
    filterFields: ["category"],
    filters: [{ key: "category", label: "Category", options: ["Rent", "Salaries", "Technology", "Professional fees", "Utilities"] }],
    defaultSort: "amount:desc",
    columns: [
      { key: "name", label: "Expense", emphasis: true },
      { key: "category", label: "Category" },
      { key: "amount", label: "Monthly amount", type: "currency", sortable: true },
      { key: "recurrence", label: "Recurrence" },
      { key: "effectiveFrom", label: "Effective from", type: "date" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: {
      fields: [
        { name: "name", label: "Expense name", type: "text", required: true },
        { name: "category", label: "Category", type: "select", options: ["Rent", "Salaries", "Technology", "Professional fees", "Utilities"], required: true },
        { name: "amount", label: "Monthly amount (₹)", type: "number", required: true, min: 1 },
        { name: "effectiveFrom", label: "Effective from", type: "date", required: true },
      ],
      defaults: { recurrence: "Monthly", status: "Active" },
      requireReason: true,
    },
  },
  "finance.wallet": {
    title: "Wallet Withdrawals",
    description: "Customer wallet withdrawal requests (₹1–25). The balance is debited when the request is raised; finance marks it paid.",
    permission: "finance.wallet",
    collection: "walletWithdrawals",
    api: "GET /api/admin/finance/wallet-withdrawals",
    searchFields: ["id", "customer"],
    tabs: { field: "status", values: ["Requested", "Paid", "Rejected"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Request", type: "mono" },
      { key: "customer", label: "Customer", href: "/admin/customers/{customerId}" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "balanceAfter", label: "Balance after", type: "currency" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Requested", type: "datetime", sortable: true },
    ],
    rowActions: [
      { id: "paid", label: "Mark paid", permission: "edit", effect: { set: { status: "Paid" } }, when: { field: "status", in: ["Requested"] }, confirm: { title: "Mark withdrawal paid?", description: "Confirm the bank transfer to the customer is complete.", requireReason: true } },
      { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { status: "Rejected" } }, when: { field: "status", in: ["Requested"] }, confirm: { title: "Reject withdrawal?", description: "The amount is credited back to the wallet by the server.", requireReason: true } },
    ],
  },
  "customers.coupons": {
    title: "Coupons",
    description: "Checkout coupons: user type (new / old / all), cart value range, percentage or flat.",
    permission: "customers.coupons",
    collection: "coupons",
    api: "GET/POST /api/admin/coupons",
    search: "Search coupon code",
    searchFields: ["code"],
    filterFields: ["status", "userType"],
    filters: [{ key: "userType", label: "User type", options: ["New", "Existing", "All"] }],
    tabs: { field: "status", values: ["Active", "Inactive"] },
    columns: [
      { key: "code", label: "Code", type: "mono", emphasis: true },
      { key: "type", label: "Type" },
      { key: "value", label: "Value", type: "number" },
      { key: "userType", label: "User type" },
      { key: "minPrice", label: "Min cart", type: "currency" },
      { key: "applyType", label: "Applies to" },
      { key: "used", label: "Used", type: "number", sortable: true },
      { key: "expiresAt", label: "Expires", type: "date", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "edit", label: "Edit", kind: "form", permission: "edit" },
      { id: "activate", label: "Activate", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", in: ["Inactive"] } },
      { id: "deactivate", label: "Deactivate", permission: "edit", tone: "danger", effect: { set: { status: "Inactive" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Deactivate coupon?", description: "Customers can no longer apply it." } },
      deleteAction,
    ],
    form: {
      fields: [
        { name: "code", label: "Coupon code", type: "text", required: true, pattern: "^[A-Z0-9]{4,15}$", patternMessage: "4–15 uppercase letters or numbers." },
        { name: "type", label: "Discount type", type: "select", options: ["Percent", "Flat"], required: true },
        { name: "value", label: "Value", type: "number", required: true, min: 1 },
        { name: "userType", label: "User type", type: "select", options: ["All", "New", "Existing"], required: true },
        { name: "minPrice", label: "Minimum cart (₹)", type: "number", min: 0, required: true },
        { name: "expiresAt", label: "Expires on", type: "date", required: true },
      ],
      defaults: { status: "Active", used: 0, applyType: "range", maxPrice: 50000 },
    },
  },
  "customers.reviews": {
    title: "Product Reviews",
    description: "Customer reviews awaiting moderation before they appear on product pages.",
    permission: "customers.reviews",
    collection: "reviews",
    api: "GET /api/admin/reviews",
    search: "Search product or customer",
    searchFields: ["product", "customer", "comment"],
    filterFields: ["rating"],
    filters: [{ key: "rating", label: "Rating", options: ["5", "4", "3", "2", "1"] }],
    tabs: { field: "status", values: ["Pending", "Published", "Hidden"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "product", label: "Product", width: 260, href: "/admin/products/{productId}" },
      { key: "customer", label: "Customer" },
      { key: "rating", label: "Rating", type: "number", sortable: true },
      { key: "comment", label: "Comment", width: 300, wrap: true },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Date", type: "date", sortable: true },
    ],
    rowActions: [
      { id: "publish", label: "Publish", permission: "edit", effect: { set: { status: "Published" } }, when: { field: "status", notIn: ["Published"] } },
      { id: "hide", label: "Hide", permission: "edit", tone: "danger", effect: { set: { status: "Hidden" } }, when: { field: "status", notIn: ["Hidden"] }, confirm: { title: "Hide review?", description: "It will no longer show on the product page." } },
    ],
    bulkActions: [{ id: "publish", label: "Publish", permission: "edit", effect: { set: { status: "Published" } } }],
  },
};
