const deleteAction = { id: "delete", label: "Delete", permission: "delete", tone: "danger", effect: { remove: true }, confirm: { title: "Delete permanently?", description: "This cannot be undone." } };
const activeToggle = [
  { id: "activate", label: "Activate", permission: "edit", effect: { set: { status: "Active" } }, when: { field: "status", notIn: ["Active"] } },
  { id: "deactivate", label: "Deactivate", permission: "edit", tone: "danger", effect: { set: { status: "Inactive" } }, when: { field: "status", in: ["Active"] }, confirm: { title: "Deactivate?", description: "The rule stops applying at checkout immediately." } },
];
const zones = ["within_city", "within_state", "metro_to_metro", "rest_of_india", "north_east_jk"];

export const orderResources = {
  "orders.invoices": {
    title: "Invoices",
    description: "Seller invoices (INV-…) per order line and the platform invoice (BAL-{FY}-…). PDFs are generated on the server after a login and Orders permission check.",
    permission: "orders.invoices",
    collection: "orderItems",
    api: "GET /api/admin/invoices · GET /api/admin/invoices/{id}/pdf",
    search: "Search invoice, order ID or vendor",
    searchFields: ["sellerInvoice", "platformInvoice", "orderId", "vendor", "customer"],
    filterFields: ["paymentMode"],
    filters: [{ key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] }],
    dateField: "createdAt",
    dateRange: "Invoice date",
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "sellerInvoice", label: "Seller invoice", type: "mono" },
      { key: "platformInvoice", label: "Platform invoice", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "vendor", label: "Vendor", width: 200 },
      { key: "taxable", label: "Taxable", type: "currency", sortable: true },
      { key: "cgst", label: "CGST", type: "currency" },
      { key: "sgst", label: "SGST", type: "currency" },
      { key: "igst", label: "IGST", type: "currency" },
      { key: "price", label: "Total", type: "currency", sortable: true },
      { key: "createdAt", label: "Date", type: "date", sortable: true },
    ],
  },
  "orders.transactions": {
    title: "Date-wise Transactions",
    description: "Every order line with its tax, commission and seller settlement split, for reconciliation.",
    permission: "orders.transactions",
    collection: "orderItems",
    api: "GET /api/admin/reports/transactions",
    search: "Search order, vendor or SKU",
    searchFields: ["orderId", "vendor", "sku", "productName"],
    filterFields: ["status", "paymentMode"],
    filters: [
      { key: "status", label: "Status", options: ["Delivered", "In Transit", "RTO", "Cancelled", "Return Completed"] },
      { key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] },
    ],
    dateField: "createdAt",
    dateRange: "Order date",
    defaultSort: "createdAt:desc",
    exportable: true,
    columns: [
      { key: "createdAt", label: "Date", type: "date", sortable: true },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "productName", label: "Product", width: 240, sub: "vendor" },
      { key: "qty", label: "Qty", type: "number" },
      { key: "price", label: "Gross", type: "currency", sortable: true },
      { key: "taxable", label: "Taxable", type: "currency" },
      { key: "gst", label: "GST", type: "currency" },
      { key: "commission", label: "Commission", type: "currency", sortable: true },
      { key: "tcs", label: "TCS", type: "currency" },
      { key: "nrv", label: "NRV", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  "orders.whatsapp": {
    title: "WhatsApp Orders",
    description: "Orders placed through the WhatsApp commerce bot (flow v2).",
    permission: "orders.whatsapp",
    collection: "whatsappOrders",
    api: "GET /api/admin/orders?channel=whatsapp",
    search: "Search order or customer",
    searchFields: ["id", "customer"],
    filterFields: ["paymentMode", "status"],
    filters: [{ key: "paymentMode", label: "Payment", options: ["COD", "Prepaid", "Partial"] }],
    dateField: "createdAt",
    dateRange: true,
    defaultSort: "createdAt:desc",
    rowHref: "/admin/orders/{id}",
    columns: [
      { key: "id", label: "Order ID", type: "mono" },
      { key: "customer", label: "Customer" },
      { key: "items", label: "Items", type: "number" },
      { key: "total", label: "Total", type: "currency", sortable: true },
      { key: "paymentMode", label: "Payment" },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Placed", type: "datetime", sortable: true },
    ],
  },
  "orders.srCheckout": {
    title: "Shiprocket Checkout",
    description: "Orders and abandoned carts captured through the Shiprocket SR Checkout module.",
    permission: "orders.srCheckout",
    collection: "srCheckout",
    api: "GET /api/admin/sr-checkout",
    searchFields: ["id", "customer"],
    filterFields: ["type", "status"],
    filters: [{ key: "type", label: "Type", options: ["Order", "Abandoned cart"] }],
    tabs: { field: "status", values: ["Captured", "Pending", "Recovered", "Abandoned"] },
    defaultSort: "createdAt:desc",
    columns: [
      { key: "id", label: "Reference", type: "mono" },
      { key: "type", label: "Type", type: "status" },
      { key: "customer", label: "Customer" },
      { key: "value", label: "Value", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
      { key: "createdAt", label: "Created", type: "datetime", sortable: true },
    ],
  },
  "shipping.courierSlabs": {
    title: "Courier Slab Rates",
    description: "Weight-slab freight by zone. Lookup order: variant → product → vendor → global. Total = (ship + COD handling + RTO) × 1.18.",
    permission: "shipping.rates",
    collection: "courierSlabs",
    api: "GET /api/admin/shipping/courier-slabs",
    columns: [
      { key: "slab", label: "Weight slab", emphasis: true },
      { key: "scope", label: "Scope" },
      ...zones.map((z) => ({ key: z, label: z.replace(/_/g, " "), type: "currency" })),
      { key: "additional", label: "Additional / step", type: "currency" },
      { key: "totalRestOfIndia", label: "Total (RoI, incl. RTO+GST)", type: "currency" },
    ],
    rowActions: [{ id: "edit", label: "Edit rates", kind: "form", permission: "edit" }],
    form: { fields: [...zones.map((z) => ({ name: z, label: `${z.replace(/_/g, " ")} (₹)`, type: "number", required: true, min: 0 })), { name: "additional", label: "Additional per step (₹)", type: "number", min: 0, required: true }], requireReason: true },
  },
  "shipping.slabs": {
    title: "Shipping Slabs",
    description: "COD shipping and handling by order value. Prepaid and partial orders pay no shipping or handling.",
    permission: "shipping.rates",
    collection: "shippingSlabs",
    api: "GET /api/admin/shipping/slabs",
    defaultSort: "orderValueFrom:asc",
    columns: [
      { key: "paymentMode", label: "Payment mode" },
      { key: "orderValueFrom", label: "Order value from", type: "currency", sortable: true },
      { key: "orderValueTo", label: "Order value to", type: "currency" },
      { key: "shipping", label: "Shipping fee", type: "currency" },
      { key: "codHandling", label: "COD handling", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...activeToggle, deleteAction],
    form: {
      fields: [
        { name: "orderValueFrom", label: "Order value from (₹)", type: "number", required: true, min: 0 },
        { name: "orderValueTo", label: "Order value to (₹)", type: "number", min: 0 },
        { name: "shipping", label: "Shipping fee (₹)", type: "number", required: true, min: 0 },
        { name: "codHandling", label: "COD handling (₹)", type: "number", required: true, min: 0 },
      ],
      defaults: { paymentMode: "cod", status: "Active" },
      requireReason: true,
    },
  },
  "shipping.codRules": {
    title: "COD State Rule",
    description: "COD availability per state. When “state match required” is on, multi-seller orders across states cannot use COD.",
    permission: "shipping.rules",
    collection: "codRules",
    api: "GET /api/admin/shipping/cod-rules",
    search: "Search state",
    searchFields: ["state"],
    columns: [
      { key: "state", label: "State", emphasis: true, sortable: true },
      { key: "codEnabled", label: "COD enabled", type: "boolean" },
      { key: "stateMatchRequired", label: "State match required", type: "boolean" },
      { key: "notes", label: "Notes", width: 260 },
    ],
    rowActions: [
      { id: "enable", label: "Enable COD", permission: "edit", effect: { set: { codEnabled: true } }, when: { field: "codEnabled", in: [false] } },
      { id: "disable", label: "Disable COD", permission: "edit", tone: "danger", effect: { set: { codEnabled: false } }, when: { field: "codEnabled", in: [true] }, confirm: { title: "Disable COD for this state?", description: "Customers in this state will only see prepaid options.", requireReason: true } },
    ],
  },
  "shipping.otherCharges": {
    title: "Other Charges",
    description: "Price-range packaging and shipping cost table. LBH weight = L×B×H / 5000 × 1000; RTO % = shipping × 2% × 25.",
    permission: "shipping.rates",
    collection: "otherCharges",
    api: "GET /api/get_other_charges.php → /api/admin/shipping/other-charges",
    filterFields: ["status"],
    filters: [{ key: "status", label: "Status", options: ["Active", "Inactive"] }],
    defaultSort: "priceMin:asc",
    columns: [
      { key: "priceMin", label: "Price min", type: "currency", sortable: true },
      { key: "priceMax", label: "Price max", type: "currency" },
      { key: "length", label: "L (cm)", type: "number" },
      { key: "breadth", label: "B (cm)", type: "number" },
      { key: "height", label: "H (cm)", type: "number" },
      { key: "weightGrams", label: "Weight (g)", type: "number" },
      { key: "lbhWeight", label: "LBH weight (g)", type: "number" },
      { key: "shippingCost", label: "Shipping", type: "currency" },
      { key: "codHandling", label: "COD", type: "currency" },
      { key: "rtoPercent", label: "RTO", type: "currency" },
      { key: "total", label: "Total", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, ...activeToggle, deleteAction],
    form: {
      fields: [
        { name: "priceMin", label: "Price min (₹)", type: "number", required: true, min: 0 },
        { name: "priceMax", label: "Price max (₹)", type: "number", required: true, min: 1 },
        { name: "length", label: "Length (cm)", type: "number", required: true, min: 1 },
        { name: "breadth", label: "Breadth (cm)", type: "number", required: true, min: 1 },
        { name: "height", label: "Height (cm)", type: "number", required: true, min: 1 },
        { name: "weightGrams", label: "Weight after packaging (g)", type: "number", required: true, min: 1 },
        { name: "shippingCost", label: "Shipping cost (₹)", type: "number", required: true, min: 0 },
        { name: "codHandling", label: "COD handling (₹)", type: "number", required: true, min: 0 },
      ],
      defaults: { status: "Active" },
      derive: "otherCharges",
    },
  },
  "shipping.boxes": {
    title: "Package Boxes",
    description: "Vendor box sizes. The smallest approved box that fits is chosen when creating a shipment.",
    permission: "shipping.boxes",
    collection: "packageBoxes",
    api: "GET /api/admin/shipping/package-boxes",
    search: "Search vendor or box code",
    searchFields: ["vendor", "code"],
    tabs: { field: "status", values: ["Approved", "Pending", "Rejected"] },
    columns: [
      { key: "code", label: "Box", type: "mono" },
      { key: "vendor", label: "Vendor", width: 220 },
      { key: "length", label: "L", type: "number" },
      { key: "breadth", label: "B", type: "number" },
      { key: "height", label: "H", type: "number" },
      { key: "maxWeightKg", label: "Max kg", type: "number" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "approve", label: "Approve", permission: "edit", effect: { set: { status: "Approved" } }, when: { field: "status", in: ["Pending"] } },
      { id: "reject", label: "Reject", permission: "edit", tone: "danger", effect: { set: { status: "Rejected" } }, when: { field: "status", in: ["Pending"] }, confirm: { title: "Reject box?", description: "The vendor will be asked to submit a new size.", requireReason: true } },
    ],
    bulkActions: [{ id: "approve", label: "Approve", permission: "edit", effect: { set: { status: "Approved" } } }],
  },
  "shipping.weight": {
    title: "Weight Discrepancy",
    description: "Read-only view from the shipping microservice. The legacy system has no dispute workflow.",
    permission: "shipping.weight",
    collection: "weightDiscrepancies",
    api: "GET ship.bharatagrolink.com/weight-discrepancy (proxied)",
    search: "Search AWB, order or vendor",
    searchFields: ["awb", "orderId", "vendor"],
    filterFields: ["courier", "status"],
    filters: [{ key: "courier", label: "Courier", options: ["NimbusPost", "Shiprocket", "Delhivery"] }],
    defaultSort: "extraCharge:desc",
    columns: [
      { key: "awb", label: "AWB", type: "mono" },
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "courier", label: "Courier" },
      { key: "vendor", label: "Vendor", width: 200 },
      { key: "declaredKg", label: "Declared kg", type: "number" },
      { key: "chargedKg", label: "Charged kg", type: "number" },
      { key: "extraCharge", label: "Extra charge", type: "currency", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
  },
  "shipping.pincodes": {
    title: "Pincode Serviceability",
    description: "Serviceable pincodes, zone, COD availability and courier coverage.",
    permission: "shipping.pincodes",
    collection: "pincodes",
    api: "GET /api/admin/shipping/pincodes",
    search: "Search pincode, city or state",
    searchFields: ["pincode", "city", "state"],
    filterFields: ["zone"],
    filters: [{ key: "zone", label: "Zone", options: zones }],
    columns: [
      { key: "pincode", label: "Pincode", type: "mono", sortable: true },
      { key: "city", label: "City", sortable: true },
      { key: "state", label: "State" },
      { key: "zone", label: "Zone" },
      { key: "cod", label: "COD", type: "boolean" },
      { key: "couriers", label: "Couriers" },
      { key: "tatDays", label: "TAT (days)", type: "number" },
    ],
  },
  "returns.reasons": {
    title: "Return Reasons",
    description: "Reasons offered when creating a return request.",
    permission: "returns",
    collection: "returnReasonRows",
    api: "GET /api/admin/returns/reasons",
    columns: [
      { key: "reason", label: "Reason", emphasis: true },
      { key: "count", label: "Returns", type: "number", sortable: true },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [{ id: "edit", label: "Edit", kind: "form", permission: "edit" }, deleteAction],
    form: { fields: [{ name: "reason", label: "Reason", type: "text", required: true, maxLength: 80 }], defaults: { status: "Active", count: 0 } },
  },
  "payouts.items": {
    title: "Payout Items",
    description: "Delivered order lines copied into vendor payouts. BSA = NRV − TCS (1% of taxable) is the amount paid to the seller.",
    permission: "payouts",
    collection: "payoutItems",
    api: "GET /api/payout/* → /api/admin/payouts/items",
    search: "Search order, vendor or product",
    searchFields: ["orderId", "vendor", "product", "payoutId"],
    filterFields: ["status", "cycle"],
    tabs: { field: "status", values: ["Pending", "On Hold", "Paid"] },
    dateField: "deliveryDate",
    dateRange: "Delivered",
    defaultSort: "deliveryDate:desc",
    exportable: true,
    columns: [
      { key: "orderId", label: "Order", type: "mono", href: "/admin/orders/{orderId}" },
      { key: "product", label: "Product", width: 240, sub: "vendor" },
      { key: "cycle", label: "Cycle" },
      { key: "gross", label: "Gross", type: "currency", sortable: true },
      { key: "taxable", label: "Taxable", type: "currency" },
      { key: "nrv", label: "NRV", type: "currency" },
      { key: "tcs", label: "TCS", type: "currency" },
      { key: "bsa", label: "BSA (payable)", type: "currency", sortable: true },
      { key: "payoutId", label: "Payout", type: "mono", href: "/admin/payouts/{payoutId}" },
      { key: "status", label: "Status", type: "status" },
    ],
    rowActions: [
      { id: "hold", label: "Put on hold", permission: "edit", effect: { set: { status: "On Hold" } }, when: { field: "status", in: ["Pending"] }, confirm: { title: "Hold this item?", description: "It will be excluded from payment until released.", requireReason: true } },
      { id: "release", label: "Release hold", permission: "edit", effect: { set: { status: "Pending" } }, when: { field: "status", in: ["On Hold"] }, confirm: { title: "Release hold?", description: "The item becomes payable in its cycle.", requireReason: true } },
    ],
  },
  "payouts.access": {
    title: "Payout Access Settings",
    description: "Controls whether each vendor can see the payout page in the seller panel.",
    permission: "payouts.access",
    collection: "vendors",
    api: "GET/PATCH /api/admin/vendors/{id}/payout-access",
    search: "Search vendor",
    searchFields: ["name", "id"],
    filterFields: ["status"],
    columns: [
      { key: "name", label: "Vendor", emphasis: true, sub: "id" },
      { key: "status", label: "Vendor status", type: "status" },
      { key: "payoutAccess", label: "Payout page access", type: "boolean", trueLabel: "Enabled", falseLabel: "Disabled" },
    ],
    rowActions: [
      { id: "enable", label: "Enable access", permission: "edit", effect: { set: { payoutAccess: true } }, when: { field: "payoutAccess", in: [false] } },
      { id: "disable", label: "Disable access", permission: "edit", tone: "danger", effect: { set: { payoutAccess: false } }, when: { field: "payoutAccess", in: [true] }, confirm: { title: "Disable payout access?", description: "The vendor will no longer see payouts in the seller panel.", requireReason: true } },
    ],
    bulkActions: [{ id: "enable", label: "Enable access", permission: "edit", effect: { set: { payoutAccess: true } } }],
  },
  "payouts.legacy": {
    title: "Legacy Payments",
    description: "Read-only weekly payments from the old payment_cron system (seller_pay = price × qty − TCS − admin profit − 18% GST on profit). Superseded by payout cycles.",
    permission: "payouts",
    collection: "legacyPayments",
    api: "GET /api/admin/payouts/legacy",
    searchFields: ["vendor"],
    columns: [
      { key: "id", label: "Payment", type: "mono" },
      { key: "vendor", label: "Vendor" },
      { key: "week", label: "Week" },
      { key: "sellerPay", label: "Seller pay", type: "currency" },
      { key: "status", label: "Status", type: "status" },
    ],
  },
};
